package api

import "testing"

// Parity vectors generated by EXECUTING the Python implementation
// (regwatch.common.text_normalize + watchlist._identity_attr) on 2026-07-21.
// If a case fails here after editing textnorm.go, the Go side has diverged
// from the normalization the daily watch cron still writes with -- fix the
// Go, or change both sides and regenerate these vectors together.

func TestCanonicalAndStrippedNameParity(t *testing.T) {
	cases := []struct {
		raw, canon, strip string
	}{
		{"Potassium Chloride", "potassium chloride", ""},
		{"HYDROCODONE BITARTRATE AND ACETAMINOPHEN", "acetaminophen; hydrocodone bitartrate", "acetaminophen; hydrocodone"},
		{"amlodipine besylate/atorvastatin calcium", "amlodipine besylate; atorvastatin calcium", "amlodipine; atorvastatin"},
		{"Drospirenone; Ethinyl Estradiol", "drospirenone; ethinyl estradiol", "drospirenone; ethinyl estradiol"},
		{"Insulin Glargine (rDNA origin)", "insulin glargine", "insulin glargine"},
		{"(whole parens)", "", ""},
		{"  Metformin   Hydrochloride  ", "metformin hydrochloride", "metformin"},
		{"a, b", "a; b", "a; b"},
		{"x and y and z", "x; y; z", "x; y; z"},
		{"Sodium Chloride", "sodium chloride", ""},
		{"Calcium Carbonate; Magnesium Hydroxide", "calcium carbonate; magnesium hydroxide", "hydroxide"},
		{"ALBUTEROL SULFATE", "albuterol sulfate", "albuterol"},
		{"budesonide;formoterol fumarate dihydrate", "budesonide; formoterol fumarate dihydrate", "budesonide; formoterol"},
		{"Ferrous Sulfate, Folic Acid", "ferrous sulfate; folic acid", "ferrous; folic acid"},
		// "\s+and\s+" separates only whitespace-delimited "and": "sand and
		// gravel" splits, "band" must not.
		{"sand and gravel", "gravel; sand", "gravel; sand"},
		{"band", "band", "band"},
		{"", "", ""},
		{"   ", "", ""},
		{"Semaglutide", "semaglutide", "semaglutide"},
		{"Naloxone HCl / Buprenorphine HCl", "buprenorphine hcl; naloxone hcl", "buprenorphine; naloxone"},
		// Python str.lower() is FULL Unicode lowercasing: U+0130 expands to
		// "i"+U+0307 and trailing capital sigma takes the final form. These
		// pin the cases.Lower choice over strings.ToLower, which gets both
		// wrong -- normalized_name is the cross-runtime identity key.
		{"İbuprofen", "i̇buprofen", "i̇buprofen"},
		{"ΑΣ", "ας", "ας"},
		{"Straße", "straße", "straße"},
	}
	for _, c := range cases {
		if got := canonicalName(c.raw); got != c.canon {
			t.Errorf("canonicalName(%q) = %q, want %q", c.raw, got, c.canon)
		}
		if got := strippedName(c.raw); got != c.strip {
			t.Errorf("strippedName(%q) = %q, want %q", c.raw, got, c.strip)
		}
	}
}

func TestIdentityAttrParity(t *testing.T) {
	sp := func(s string) *string { return &s }
	cases := []struct {
		in, want *string
	}{
		{nil, nil},
		{sp(""), sp("")},
		{sp("  Tablet  "), sp("tablet")},
		{sp("TABLET"), sp("tablet")},
		{sp("Extended  Release\tTablet"), sp("extended release tablet")},
		// Python str.casefold is FULL folding: U+0130 -> "i" + combining dot
		// (2 runes), ess-zed -> "ss". strings.ToLower gets both wrong; these
		// two vectors pin the cases.Fold choice.
		{sp("İstanbul"), sp("i̇stanbul")},
		{sp("Straße"), sp("strasse")},
		{sp("ORAL-21"), sp("oral-21")},
	}
	for _, c := range cases {
		got := identityAttr(c.in)
		switch {
		case got == nil && c.want == nil:
		case got == nil || c.want == nil || *got != *c.want:
			t.Errorf("identityAttr(%v) = %v, want %v", strOrNil(c.in), strOrNil(got), strOrNil(c.want))
		}
	}
}

func strOrNil(p *string) any {
	if p == nil {
		return "<nil>"
	}
	return *p
}

func TestIdentityAttrEqual(t *testing.T) {
	sp := func(s string) *string { return &s }
	cases := []struct {
		a, b *string
		want bool
	}{
		{nil, nil, true},
		{nil, sp("Tablet"), false}, // unknown matches only unknown
		{sp("Tablet"), nil, false},
		{sp("Tablet"), sp("TABLET"), true},
		{sp(" Oral "), sp("oral"), true},
		{sp("Tablet"), sp("Tablet ER"), false},
		{sp(""), sp(""), true},
		{nil, sp(""), false}, // None vs "" are DISTINCT identities in Python
	}
	for _, c := range cases {
		if got := identityAttrEqual(c.a, c.b); got != c.want {
			t.Errorf("identityAttrEqual(%v, %v) = %v, want %v", strOrNil(c.a), strOrNil(c.b), got, c.want)
		}
	}
}

// orStr carries Python `or` semantics -- empty string is falsy. The merge
// trust gate depends on this; a nil-only implementation would let a
// lower-trust import "fill" a field the user deliberately blanked.
func TestOrStrEmptyStringFalsy(t *testing.T) {
	sp := func(s string) *string { return &s }
	cases := []struct {
		a, b, want *string
	}{
		{sp("x"), sp("y"), sp("x")},
		{nil, sp("y"), sp("y")},
		{sp(""), sp("y"), sp("y")},
		{sp(""), nil, nil},
		{nil, sp(""), sp("")},
		{nil, nil, nil},
	}
	for _, c := range cases {
		got := orStr(c.a, c.b)
		switch {
		case got == nil && c.want == nil:
		case got == nil || c.want == nil || *got != *c.want:
			t.Errorf("orStr(%v, %v) = %v, want %v", strOrNil(c.a), strOrNil(c.b), strOrNil(got), strOrNil(c.want))
		}
	}
}
