package api

// Port of src/regwatch/common/text_normalize.py (canonicalName/strippedName)
// and watchlist.py::_identity_attr. This is one of the system's most
// failure-prone surfaces (name matching): the daily watch cron and any future
// Python drugsfda re-import match products on the normalized_name column this
// package now WRITES, so a divergent normalization would mint duplicate
// identity rows and fan out duplicate alerts per PSG. textnorm_test.go pins
// parity against vectors generated by executing the Python implementation.
//
// Known deliberate divergence: Go RE2's \s is ASCII while Python's re \s is
// Unicode-aware -- ingredient names are ASCII in practice, and both sides
// TrimSpace/strip with Unicode semantics, so only exotic interior Unicode
// whitespace could differ.

import (
	"regexp"
	"sort"
	"strings"

	"golang.org/x/text/cases"
	"golang.org/x/text/language"
)

// saltTokens mirrors SALT_TOKENS: salt/hydrate suffixes stripped for the
// secondary lookup key, including the anion list that makes mono-salts like
// "Potassium Chloride" strip to "" so the empty-key guard refuses matches.
var saltTokens = map[string]bool{
	"hydrochloride": true, "hcl": true, "sulfate": true, "sulphate": true,
	"bitartrate": true, "tartrate": true, "citrate": true, "phosphate": true,
	"fumarate": true, "succinate": true, "mesylate": true, "dimesylate": true,
	"tosylate": true, "besylate": true, "sodium": true, "potassium": true,
	"calcium": true, "magnesium": true, "monohydrate": true, "dihydrate": true,
	"trihydrate": true, "anhydrous": true, "chloride": true, "bromide": true,
	"iodide": true, "acetate": true, "gluconate": true, "lactate": true,
	"carbonate": true, "bicarbonate": true,
}

var (
	sepRe   = regexp.MustCompile(`(?i)[;/]|(?:\s+and\s+)|(?:\s*,\s*)`)
	parenRe = regexp.MustCompile(`\(([^)]*)\)`)
	wsRe    = regexp.MustCompile(`\s+`)
	// Python str.casefold is FULL Unicode case folding (x/text cases.Fold),
	// not the simple folding of strings.ToLower. cases.Fold() is documented
	// stateless and goroutine-safe, so one shared Caser is fine here.
	foldCaser = cases.Fold()
)

// lower is Python str.lower(): FULL Unicode lowercasing (SpecialCasing.txt,
// e.g. U+0130 -> "i"+U+0307, plus context-sensitive final sigma), which
// strings.ToLower's simple per-rune mapping gets wrong. normalized_name is
// the cross-runtime identity column, so the mapping must match Python's
// exactly (pinned by the parity vectors). Unlike Fold, a Lower Caser is NOT
// documented goroutine-safe, so it is constructed per call.
func lower(s string) string {
	return cases.Lower(language.Und).String(s)
}

func splitIngredients(raw string) []string {
	var parts []string
	for _, p := range sepRe.Split(raw, -1) {
		if p = strings.TrimSpace(p); p != "" {
			parts = append(parts, p)
		}
	}
	return parts
}

func cleanPart(part string) string {
	cleaned := parenRe.ReplaceAllString(part, " ")
	cleaned = wsRe.ReplaceAllString(cleaned, " ")
	return lower(strings.TrimSpace(cleaned))
}

// canonicalName: lowercased, whitespace-collapsed, salt-preserving, sorted
// parts joined by "; " -- the value POST /products writes to normalized_name.
func canonicalName(raw string) string {
	var parts []string
	for _, part := range splitIngredients(raw) {
		if cleaned := cleanPart(part); cleaned != "" {
			parts = append(parts, cleaned)
		}
	}
	sort.Strings(parts)
	return strings.Join(parts, "; ")
}

// strippedName: the salt-stripped lowercase secondary key, computed AT READ
// TIME for every product wire row (it is not a DB column).
func strippedName(raw string) string {
	var parts []string
	for _, part := range splitIngredients(raw) {
		cleaned := cleanPart(part)
		if cleaned == "" {
			continue
		}
		var tokens []string
		for _, t := range strings.Split(cleaned, " ") {
			if t != "" && !saltTokens[t] {
				tokens = append(tokens, t)
			}
		}
		if len(tokens) > 0 {
			parts = append(parts, strings.Join(tokens, " "))
		}
	}
	sort.Strings(parts)
	return strings.Join(parts, "; ")
}

// identityAttr ports watchlist.py::_identity_attr: casefold + collapse
// whitespace for the upsert identity key; nil stays nil (an unknown
// form/route matches only another unknown).
func identityAttr(value *string) *string {
	if value == nil {
		return nil
	}
	folded := foldCaser.String(strings.TrimSpace(*value))
	out := strings.Join(strings.Fields(folded), " ")
	return &out
}

func identityAttrEqual(a, b *string) bool {
	na, nb := identityAttr(a), identityAttr(b)
	if na == nil || nb == nil {
		return na == nil && nb == nil
	}
	return *na == *nb
}
