// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuthSession = `-- name: CreateAuthSession :one
INSERT INTO public.auth_session (token_hash, user_id, created_at, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type CreateAuthSessionParams struct {
	TokenHash string
	UserID    int32
	CreatedAt pgtype.Timestamp
	ExpiresAt pgtype.Timestamp
}

func (q *Queries) CreateAuthSession(ctx context.Context, arg CreateAuthSessionParams) (int32, error) {
	row := q.db.QueryRow(ctx, createAuthSession,
		arg.TokenHash,
		arg.UserID,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const deleteAuthSessionByTokenHash = `-- name: DeleteAuthSessionByTokenHash :execrows
DELETE FROM public.auth_session
WHERE token_hash = $1
`

// Logout / revoke: silent when the row is already gone (rows tells the caller).
func (q *Queries) DeleteAuthSessionByTokenHash(ctx context.Context, tokenHash string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAuthSessionByTokenHash, tokenHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredAuthSessions = `-- name: DeleteExpiredAuthSessions :execrows
DELETE FROM public.auth_session
WHERE expires_at < $1
`

// Login-time sweep of expired rows (sessions.py:80-81 -- login is the only
// periodic cleanup; the cutoff is a parameter so tests control the clock).
func (q *Queries) DeleteExpiredAuthSessions(ctx context.Context, expiresAt pgtype.Timestamp) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredAuthSessions, expiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAuthSessionWithUser = `-- name: GetAuthSessionWithUser :one
SELECT s.id AS session_id,
       s.expires_at,
       s.last_seen_at,
       u.id AS user_id,
       u.email,
       u.display_name,
       u.role,
       u.is_active
FROM public.auth_session s
JOIN public."user" u ON u.id = s.user_id
WHERE s.token_hash = $1
`

type GetAuthSessionWithUserRow struct {
	SessionID   int32
	ExpiresAt   pgtype.Timestamp
	LastSeenAt  pgtype.Timestamp
	UserID      int32
	Email       string
	DisplayName string
	Role        string
	IsActive    bool
}

// resolve_token's lookup: one round trip for session + user. The caller
// rejects expired rows and inactive users; a miss here is simply "no session".
func (q *Queries) GetAuthSessionWithUser(ctx context.Context, tokenHash string) (GetAuthSessionWithUserRow, error) {
	row := q.db.QueryRow(ctx, getAuthSessionWithUser, tokenHash)
	var i GetAuthSessionWithUserRow
	err := row.Scan(
		&i.SessionID,
		&i.ExpiresAt,
		&i.LastSeenAt,
		&i.UserID,
		&i.Email,
		&i.DisplayName,
		&i.Role,
		&i.IsActive,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one

SELECT id, email, password_hash, display_name, role, is_active, created_at FROM public."user"
WHERE email = $1
`

// Auth store surface: opaque-cookie sessions (auth_session) + "user".
// Semantics mirror src/regwatch/auth/sessions.py. POLICY STAYS IN CODE: these
// queries only move rows -- expiry rejection, is_active rejection, uniform
// bcrypt timing, and the last_seen 5-minute coalesce all live in the handler
// layer (PR B), exactly where Python keeps them today.
func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const touchAuthSessionLastSeen = `-- name: TouchAuthSessionLastSeen :exec
UPDATE public.auth_session
SET last_seen_at = $2
WHERE token_hash = $1
`

type TouchAuthSessionLastSeenParams struct {
	TokenHash  string
	LastSeenAt pgtype.Timestamp
}

func (q *Queries) TouchAuthSessionLastSeen(ctx context.Context, arg TouchAuthSessionLastSeenParams) error {
	_, err := q.db.Exec(ctx, touchAuthSessionLastSeen, arg.TokenHash, arg.LastSeenAt)
	return err
}
