// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chat.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countChatMessagesForUser = `-- name: CountChatMessagesForUser :many
SELECT cm.session_id,
       COUNT(*)::bigint AS message_count
FROM public.chat_message cm
JOIN public.chat_session cs ON cs.id = cm.session_id
WHERE cs.user_id = $1
GROUP BY cm.session_id
`

type CountChatMessagesForUserRow struct {
	SessionID    string
	MessageCount int64
}

func (q *Queries) CountChatMessagesForUser(ctx context.Context, userID pgtype.Text) ([]CountChatMessagesForUserRow, error) {
	rows, err := q.db.Query(ctx, countChatMessagesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountChatMessagesForUserRow
	for rows.Next() {
		var i CountChatMessagesForUserRow
		if err := rows.Scan(&i.SessionID, &i.MessageCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteChatMessagesBySession = `-- name: DeleteChatMessagesBySession :execrows
DELETE FROM public.chat_message
WHERE session_id = $1
`

// Hard delete, messages first (chat_message.session_id FK has no ON DELETE
// CASCADE -- the order here is load-bearing, same as the Python handler).
func (q *Queries) DeleteChatMessagesBySession(ctx context.Context, sessionID string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteChatMessagesBySession, sessionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteChatSession = `-- name: DeleteChatSession :execrows
DELETE FROM public.chat_session
WHERE id = $1
`

func (q *Queries) DeleteChatSession(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteChatSession, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getChatSessionOwned = `-- name: GetChatSessionOwned :one
SELECT id, user_id, title, active_filters_json, created_at, updated_at FROM public.chat_session
WHERE id = $1 AND user_id = $2
`

type GetChatSessionOwnedParams struct {
	ID     string
	UserID pgtype.Text
}

func (q *Queries) GetChatSessionOwned(ctx context.Context, arg GetChatSessionOwnedParams) (ChatSession, error) {
	row := q.db.QueryRow(ctx, getChatSessionOwned, arg.ID, arg.UserID)
	var i ChatSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.ActiveFiltersJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listChatMessages = `-- name: ListChatMessages :many
SELECT id, session_id, turn_id, role, content, status, model_name, audit_id, reason, interpretation, filters_json, citations_json, clarify_json, related_json, metadata_json, created_at FROM public.chat_message
WHERE session_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListChatMessages(ctx context.Context, sessionID string) ([]ChatMessage, error) {
	rows, err := q.db.Query(ctx, listChatMessages, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatMessage
	for rows.Next() {
		var i ChatMessage
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.TurnID,
			&i.Role,
			&i.Content,
			&i.Status,
			&i.ModelName,
			&i.AuditID,
			&i.Reason,
			&i.Interpretation,
			&i.FiltersJson,
			&i.CitationsJson,
			&i.ClarifyJson,
			&i.RelatedJson,
			&i.MetadataJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChatSessionsForUser = `-- name: ListChatSessionsForUser :many

SELECT cs.id,
       cs.user_id,
       cs.title,
       cs.active_filters_json,
       cs.created_at,
       cs.updated_at,
       COALESCE(cs.title, (
         SELECT cm.content
         FROM public.chat_message cm
         WHERE cm.session_id = cs.id AND cm.role = 'user'
         ORDER BY cm.created_at ASC
         LIMIT 1
       )) AS display_title
FROM public.chat_session cs
WHERE cs.user_id = $1
ORDER BY cs.updated_at DESC
`

type ListChatSessionsForUserRow struct {
	ID                string
	UserID            pgtype.Text
	Title             pgtype.Text
	ActiveFiltersJson []byte
	CreatedAt         pgtype.Timestamp
	UpdatedAt         pgtype.Timestamp
	DisplayTitle      pgtype.Text
}

// Chat session/message store surface for GET/DELETE /sessions*.
// Mirrors src/regwatch/api/main.py list_sessions/get_session/delete_session:
// the list page is DELIBERATELY two queries (sessions + one GROUP BY of
// message counts), never N+1; ownership is enforced by scoping every query
// to user_id and treating a miss as 404 (never 403 -- foreign rows must not
// be confirmed to exist).
// display_title falls back to the first user message's content when the
// session has no explicit title (the correlated subquery the Python list
// endpoint uses). NULL when a session has neither -- the wire mapping owns
// what to render then. COALESCE vs Python truthiness: an EMPTY-STRING title
// would coalesce here but fall through in Python; unreachable today (nothing
// in src/ ever writes title), revisit if a rename/title feature lands.
func (q *Queries) ListChatSessionsForUser(ctx context.Context, userID pgtype.Text) ([]ListChatSessionsForUserRow, error) {
	rows, err := q.db.Query(ctx, listChatSessionsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChatSessionsForUserRow
	for rows.Next() {
		var i ListChatSessionsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.ActiveFiltersJson,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DisplayTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
