// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AnswerFeedback struct {
	ID        int32
	AuditID   int32
	UserID    string
	Rating    int32
	Comment   pgtype.Text
	CreatedAt pgtype.Timestamp
}

type AuthSession struct {
	ID         int32
	TokenHash  string
	UserID     int32
	CreatedAt  pgtype.Timestamp
	ExpiresAt  pgtype.Timestamp
	LastSeenAt pgtype.Timestamp
}

type ChatMessage struct {
	ID             string
	SessionID      string
	TurnID         string
	Role           string
	Content        string
	Status         pgtype.Text
	ModelName      pgtype.Text
	AuditID        pgtype.Int4
	Reason         pgtype.Text
	Interpretation pgtype.Text
	FiltersJson    []byte
	CitationsJson  []byte
	ClarifyJson    []byte
	RelatedJson    []byte
	MetadataJson   []byte
	CreatedAt      pgtype.Timestamp
}

type ChatSession struct {
	ID                string
	UserID            pgtype.Text
	Title             pgtype.Text
	ActiveFiltersJson []byte
	Origin            string
	CreatedAt         pgtype.Timestamp
	UpdatedAt         pgtype.Timestamp
}

type Product struct {
	ID                   int32
	ActiveIngredient     string
	NormalizedName       string
	DosageForm           pgtype.Text
	Route                pgtype.Text
	RldName              pgtype.Text
	RldApplicationNumber pgtype.Text
	CompanyStatus        pgtype.Text
	Source               string
	SourceUrl            pgtype.Text
	OnWatchlist          bool
	AddedAt              pgtype.Timestamp
}

type QueryLog struct {
	ID            int32
	Ts            pgtype.Timestamp
	SessionID     pgtype.Text
	TurnID        pgtype.Text
	UserID        pgtype.Text
	Mode          string
	QueryText     string
	RetrievedJson []byte
	AnswerText    string
	CitationsJson []byte
	Refused       bool
	Status        pgtype.Text
	RouteJson     []byte
	ModelName     string
	InputTokens   pgtype.Int4
	OutputTokens  pgtype.Int4
	CostUsd       pgtype.Float8
	LatencyMs     pgtype.Int4
}

type User struct {
	ID           int32
	Email        string
	PasswordHash string
	DisplayName  string
	Role         string
	IsActive     bool
	CreatedAt    pgtype.Timestamp
}
