// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: product.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO public.product (
  active_ingredient, normalized_name, dosage_form, route, rld_name,
  rld_application_number, company_status, source, source_url,
  on_watchlist, added_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, active_ingredient, normalized_name, dosage_form, route, rld_name, rld_application_number, company_status, source, source_url, on_watchlist, added_at
`

type CreateProductParams struct {
	ActiveIngredient     string
	NormalizedName       string
	DosageForm           pgtype.Text
	Route                pgtype.Text
	RldName              pgtype.Text
	RldApplicationNumber pgtype.Text
	CompanyStatus        pgtype.Text
	Source               string
	SourceUrl            pgtype.Text
	OnWatchlist          bool
	AddedAt              pgtype.Timestamp
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.ActiveIngredient,
		arg.NormalizedName,
		arg.DosageForm,
		arg.Route,
		arg.RldName,
		arg.RldApplicationNumber,
		arg.CompanyStatus,
		arg.Source,
		arg.SourceUrl,
		arg.OnWatchlist,
		arg.AddedAt,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.ActiveIngredient,
		&i.NormalizedName,
		&i.DosageForm,
		&i.Route,
		&i.RldName,
		&i.RldApplicationNumber,
		&i.CompanyStatus,
		&i.Source,
		&i.SourceUrl,
		&i.OnWatchlist,
		&i.AddedAt,
	)
	return i, err
}

const getProduct = `-- name: GetProduct :one
SELECT id, active_ingredient, normalized_name, dosage_form, route, rld_name, rld_application_number, company_status, source, source_url, on_watchlist, added_at FROM public.product
WHERE id = $1
`

func (q *Queries) GetProduct(ctx context.Context, id int32) (Product, error) {
	row := q.db.QueryRow(ctx, getProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.ActiveIngredient,
		&i.NormalizedName,
		&i.DosageForm,
		&i.Route,
		&i.RldName,
		&i.RldApplicationNumber,
		&i.CompanyStatus,
		&i.Source,
		&i.SourceUrl,
		&i.OnWatchlist,
		&i.AddedAt,
	)
	return i, err
}

const listWatchlistProducts = `-- name: ListWatchlistProducts :many

SELECT id, active_ingredient, normalized_name, dosage_form, route, rld_name, rld_application_number, company_status, source, source_url, on_watchlist, added_at FROM public.product
WHERE on_watchlist
ORDER BY id ASC
`

// Product (org-shared watchlist) store surface for /products CRUD.
// Mirrors src/regwatch/watch/watchlist.py semantics: DELETE is a SOFT delete
// (on_watchlist=false) because alert history references product_id (INV-4);
// the INV-5 source allowlist (user-assertable sources only) is handler
// policy, not a query concern. List ordering: Python's list_watchlist() has
// NO ORDER BY (unspecified heap order), so id ASC here is a deliberate
// deterministic refinement -- PR C's contract tests pin it as the NEW order.
//
// PR C NOTE: CreateProduct alone does NOT implement POST /products. The
// Python handler runs watchlist.upsert_entries -- an identity MERGE matching
// on (normalized_name, rld_application_number) with NULL-safe comparison
// (IS NOT DISTINCT FROM) and a source-rank-gated field merge. PR C adds that
// candidate-select + merge-update pair; porting POST onto bare CreateProduct
// would mint duplicate identity rows and always report added=1.
func (q *Queries) ListWatchlistProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.Query(ctx, listWatchlistProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.ActiveIngredient,
			&i.NormalizedName,
			&i.DosageForm,
			&i.Route,
			&i.RldName,
			&i.RldApplicationNumber,
			&i.CompanyStatus,
			&i.Source,
			&i.SourceUrl,
			&i.OnWatchlist,
			&i.AddedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setProductWatchlist = `-- name: SetProductWatchlist :execrows
UPDATE public.product
SET on_watchlist = $2
WHERE id = $1
`

type SetProductWatchlistParams struct {
	ID          int32
	OnWatchlist bool
}

func (q *Queries) SetProductWatchlist(ctx context.Context, arg SetProductWatchlistParams) (int64, error) {
	result, err := q.db.Exec(ctx, setProductWatchlist, arg.ID, arg.OnWatchlist)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
