-- Generated by scripts/gen-store-schema.sh -- DO NOT EDIT BY HAND.
-- Scope: the step-4 Go store tables at Alembic head; drift-gated in CI
-- (store-schema-drift job) against a regwatch init-db bootstrap.

CREATE TABLE public.answer_feedback (
    id integer NOT NULL,
    audit_id integer NOT NULL,
    user_id character varying NOT NULL,
    rating integer NOT NULL,
    comment character varying,
    created_at timestamp without time zone NOT NULL,
    CONSTRAINT ck_answer_feedback_rating CHECK ((rating = ANY (ARRAY['-1'::integer, 1])))
);

CREATE SEQUENCE public.answer_feedback_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE public.answer_feedback_id_seq OWNED BY public.answer_feedback.id;

CREATE TABLE public.auth_session (
    id integer NOT NULL,
    token_hash character varying NOT NULL,
    user_id integer NOT NULL,
    created_at timestamp without time zone NOT NULL,
    expires_at timestamp without time zone NOT NULL,
    last_seen_at timestamp without time zone
);

CREATE SEQUENCE public.auth_session_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE public.auth_session_id_seq OWNED BY public.auth_session.id;

CREATE TABLE public.chat_message (
    id character varying NOT NULL,
    session_id character varying NOT NULL,
    turn_id character varying NOT NULL,
    role character varying NOT NULL,
    content character varying NOT NULL,
    status character varying,
    model_name character varying,
    audit_id integer,
    reason character varying,
    interpretation character varying,
    filters_json jsonb,
    citations_json jsonb,
    clarify_json jsonb,
    related_json jsonb,
    metadata_json jsonb,
    created_at timestamp without time zone NOT NULL
);

CREATE TABLE public.chat_session (
    id character varying NOT NULL,
    user_id character varying,
    title character varying,
    active_filters_json jsonb,
    origin character varying DEFAULT 'thread'::character varying NOT NULL,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL,
    CONSTRAINT ck_chat_session_origin CHECK (((origin)::text = ANY ((ARRAY['thread'::character varying, 'assistant'::character varying])::text[])))
);

CREATE TABLE public.product (
    id integer NOT NULL,
    active_ingredient character varying NOT NULL,
    normalized_name character varying NOT NULL,
    dosage_form character varying,
    route character varying,
    rld_name character varying,
    rld_application_number character varying,
    company_status character varying,
    source character varying NOT NULL,
    source_url character varying,
    on_watchlist boolean NOT NULL,
    added_at timestamp without time zone NOT NULL
);

CREATE SEQUENCE public.product_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE public.product_id_seq OWNED BY public.product.id;

CREATE TABLE public.query_log (
    id integer NOT NULL,
    ts timestamp without time zone NOT NULL,
    session_id character varying,
    turn_id character varying,
    user_id character varying,
    mode character varying NOT NULL,
    query_text character varying NOT NULL,
    retrieved_json jsonb,
    answer_text character varying NOT NULL,
    citations_json jsonb,
    refused boolean NOT NULL,
    status character varying,
    route_json jsonb,
    model_name character varying NOT NULL,
    input_tokens integer,
    output_tokens integer,
    cost_usd double precision,
    latency_ms integer
);

CREATE SEQUENCE public.query_log_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE public.query_log_id_seq OWNED BY public.query_log.id;

CREATE TABLE public."user" (
    id integer NOT NULL,
    email character varying NOT NULL,
    password_hash character varying NOT NULL,
    display_name character varying NOT NULL,
    role character varying NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp without time zone NOT NULL
);

CREATE SEQUENCE public.user_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE public.user_id_seq OWNED BY public."user".id;

ALTER TABLE ONLY public.answer_feedback ALTER COLUMN id SET DEFAULT nextval('public.answer_feedback_id_seq'::regclass);

ALTER TABLE ONLY public.auth_session ALTER COLUMN id SET DEFAULT nextval('public.auth_session_id_seq'::regclass);

ALTER TABLE ONLY public.product ALTER COLUMN id SET DEFAULT nextval('public.product_id_seq'::regclass);

ALTER TABLE ONLY public.query_log ALTER COLUMN id SET DEFAULT nextval('public.query_log_id_seq'::regclass);

ALTER TABLE ONLY public."user" ALTER COLUMN id SET DEFAULT nextval('public.user_id_seq'::regclass);

ALTER TABLE ONLY public.answer_feedback
    ADD CONSTRAINT answer_feedback_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.auth_session
    ADD CONSTRAINT auth_session_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.chat_message
    ADD CONSTRAINT chat_message_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.chat_session
    ADD CONSTRAINT chat_session_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.product
    ADD CONSTRAINT product_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.query_log
    ADD CONSTRAINT query_log_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.answer_feedback
    ADD CONSTRAINT uq_answer_feedback_audit_user UNIQUE (audit_id, user_id);

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT user_pkey PRIMARY KEY (id);

CREATE INDEX ix_answer_feedback_audit_id ON public.answer_feedback USING btree (audit_id);

CREATE INDEX ix_answer_feedback_user_id ON public.answer_feedback USING btree (user_id);

CREATE UNIQUE INDEX ix_auth_session_token_hash ON public.auth_session USING btree (token_hash);

CREATE INDEX ix_auth_session_user_id ON public.auth_session USING btree (user_id);

CREATE INDEX ix_chat_message_audit_id ON public.chat_message USING btree (audit_id);

CREATE INDEX ix_chat_message_created_at ON public.chat_message USING btree (created_at);

CREATE INDEX ix_chat_message_session_id ON public.chat_message USING btree (session_id);

CREATE INDEX ix_chat_message_turn_id ON public.chat_message USING btree (turn_id);

CREATE INDEX ix_chat_session_created_at ON public.chat_session USING btree (created_at);

CREATE INDEX ix_chat_session_updated_at ON public.chat_session USING btree (updated_at);

CREATE INDEX ix_chat_session_user_id ON public.chat_session USING btree (user_id);

CREATE INDEX ix_chat_session_user_id_updated_at ON public.chat_session USING btree (user_id, updated_at);

CREATE INDEX ix_product_normalized_name ON public.product USING btree (normalized_name);

CREATE INDEX ix_query_log_session_id ON public.query_log USING btree (session_id);

CREATE INDEX ix_query_log_ts ON public.query_log USING btree (ts);

CREATE INDEX ix_query_log_turn_id ON public.query_log USING btree (turn_id);

CREATE INDEX ix_query_log_user_id ON public.query_log USING btree (user_id);

CREATE UNIQUE INDEX ix_user_email ON public."user" USING btree (email);

ALTER TABLE ONLY public.answer_feedback
    ADD CONSTRAINT answer_feedback_audit_id_fkey FOREIGN KEY (audit_id) REFERENCES public.query_log(id);

ALTER TABLE ONLY public.auth_session
    ADD CONSTRAINT auth_session_user_id_fkey FOREIGN KEY (user_id) REFERENCES public."user"(id);

ALTER TABLE ONLY public.chat_message
    ADD CONSTRAINT chat_message_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.chat_session(id);

ALTER TABLE public.answer_feedback ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.auth_session ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.chat_message ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.chat_session ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.product ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.query_log ENABLE ROW LEVEL SECURITY;

ALTER TABLE public."user" ENABLE ROW LEVEL SECURITY;

