#!/usr/bin/env bash
#
# Regenerate the Go store's schema snapshot (go/internal/store/schema.sql).
#
# sqlc needs SQL DDL as its schema input, but this repo's schema truth is
# Alembic Python migrations -- unparseable by sqlc. So we commit a pg_dump
# snapshot SCOPED to the tables the Go store touches (an FK-closed set:
# answer_feedback -> query_log is the only edge out of the step-4 tables),
# and CI's store-schema-drift job re-runs this exact pipeline against a
# code-bootstrapped (init-db) database to prove the committed file still
# matches Alembic head. Regenerate ONLY with this script -- never hand-edit
# the output -- and always against a scratch database bootstrapped by
# `regwatch init-db` (NEVER prod: dump text would differ -- prod predates
# migration 0010's jsonb columns -- and pointing tooling at prod is how the
# 2026-07-07 incident started).
#
# Usage:
#   scripts/gen-store-schema.sh <postgres-url> [outfile]
#   PGDUMP="docker run --rm --network host -e PGPASSWORD=postgres \
#     pgvector/pgvector:pg17 pg_dump" scripts/gen-store-schema.sh <url> [outfile]
#
# The PGDUMP override exists because GitHub's ubuntu runners ship a pg_dump
# older than the pg17 service (server-version-mismatch refusal); CI runs
# pg_dump from the already-pinned service image instead of adding a new pin.
#
# Normalization: strip SET/set_config preamble, comments, psql \restrict
# guard lines (pg_dump >= 2025-08 emits them with a RANDOM key -- they would
# make every dump unique), and squash blank runs. What remains (CREATE TABLE/
# SEQUENCE, ALTER ... DEFAULT/OWNED BY/constraints/RLS, CREATE INDEX) is
# deterministic for a fixed bootstrap path, so the CI diff is stable.
set -euo pipefail

DB_URL="${1:?usage: gen-store-schema.sh <postgres-url> [outfile]}"
OUT="${2:-go/internal/store/schema.sql}"
PGDUMP="${PGDUMP:-pg_dump}"

# The Go store's table scope. Adding a table here is a DELIBERATE act: it
# widens what Go owns, must ship with the queries that need it, and the
# committed schema.sql + generated code must be regenerated in the same PR.
TABLES=(user auth_session chat_session chat_message answer_feedback query_log product)

args=()
for t in "${TABLES[@]}"; do
  args+=(-t "public.\"${t}\"")
done

{
  printf -- '-- Generated by scripts/gen-store-schema.sh -- DO NOT EDIT BY HAND.\n'
  printf -- '-- Scope: the step-4 Go store tables at Alembic head; drift-gated in CI\n'
  printf -- '-- (store-schema-drift job) against a regwatch init-db bootstrap.\n'
  # shellcheck disable=SC2086  # PGDUMP is intentionally word-split (docker run ...)
  $PGDUMP "$DB_URL" --schema-only --no-owner --no-privileges --no-comments --strict-names "${args[@]}" \
    | grep -vE '^(SET |SELECT pg_catalog\.set_config|--|\\)' \
    | cat -s
} > "$OUT"

printf 'wrote %s (%s lines)\n' "$OUT" "$(wc -l < "$OUT" | tr -d ' ')" >&2
