/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Diagnose the stack: db, chroma, providers. Superset of {"status": "ok"}.
         *
         *     503 only when the DB or Chroma is unreachable. An empty corpus is healthy
         *     (with a warning) so a fresh stack can boot and the ingest service can seed.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Revoke the server-side session and clear the cookie. Never errors.
         */
        post: operations["logout_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Query */
        post: operations["query_query_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/query/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Query Stream
         * @description Streaming twin of POST /query (Server-Sent Events).
         *
         *     Same auth, rate limit, ownership, pipeline, and single audit row as /query;
         *     it streams live progress as ``status`` frames and the SAME validated
         *     QueryResponse as one terminal ``result`` frame (both built via
         *     _build_query_response, so the shapes cannot drift). The Ask UI consumes this
         *     and transparently falls back to POST /query if the stream fails. Rate-limit
         *     (429), ownership (404), and auth (401) are enforced BEFORE the stream opens,
         *     as real HTTP statuses — never mid-stream.
         */
        post: operations["query_stream_query_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Feedback
         * @description Thumbs up/down on one of the caller's own answered Q&A turns (H4).
         *
         *     404 for a missing, foreign, or non-qa audit row — mirroring the docx
         *     ownership pattern, the response never confirms that someone else's audit
         *     row exists. Feedback rows are the candidate pool for future eval gold-set
         *     items (see README).
         */
        post: operations["feedback_feedback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sources Search */
        post: operations["sources_search_sources_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assemble": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Assemble */
        post: operations["assemble_assemble_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/whitepaper": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Whitepaper
         * @description Populate the CRA White Paper for an RLD name + NDA/ANDA number.
         *
         *     Writes one whitepaper audit row (in build_whitepaper) on success AND on a
         *     422 resolution failure. Rate-limited like /query and /assemble.
         */
        post: operations["whitepaper_whitepaper_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resolve
         * @description Resolve an RLD name + application number to the canonical spine.
         *
         *     Deterministic entity resolution, NOT an LLM turn: it writes NO audit row
         *     (success or failure) and returns no answer text — it lets a surface pin a
         *     canonical product without running a full populate. On an unresolved or
         *     mismatched application it 422s with the resolver's own detail (refuse over
         *     guess). Rate-limited like /query, /assemble, /whitepaper (it hits live FDA
         *     sources just as they do).
         */
        post: operations["resolve_resolve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/whitepaper/docx": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Whitepaper Docx
         * @description Render the Word document FROM a previously returned /whitepaper result.
         *
         *     No re-populate: zero live fetches, zero LLM calls — the .docx is rendered
         *     from the exact JSON the analyst reviewed, after verifying result.audit_id
         *     is the caller's own white-paper audit row. Writes one lightweight audit row
         *     (mode="whitepaper", docx_render) and keeps the /query rate limiter.
         */
        post: operations["whitepaper_docx_whitepaper_docx_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/watch/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Watch Latest */
        get: operations["watch_latest_watch_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Products */
        get: operations["list_products_products_get"];
        put?: never;
        /** Create Product */
        post: operations["create_product_products_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Sessions
         * @description Two queries max — network RTT amplifies per-row queries ~1000x on Postgres.
         *
         *     Query 1 is the session page with the title fallback (first user message)
         *     folded in as a correlated scalar subquery; query 2 fetches all message
         *     counts for the page via one GROUP BY. Never N+1.
         */
        get: operations["list_sessions_sessions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session */
        get: operations["get_session_sessions__session_id__get"];
        put?: never;
        post?: never;
        /** Delete Session */
        delete: operations["delete_session_sessions__session_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Public Settings */
        get: operations["get_public_settings_settings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AssembleRequest */
        AssembleRequest: {
            /** Active Ingredient */
            active_ingredient: string;
            /** Dosage Form */
            dosage_form?: string | null;
            /**
             * Rld
             * @description RLD brand name or application number
             */
            rld?: string | null;
        };
        /** AssembleResponse */
        AssembleResponse: {
            /** Markdown */
            markdown: string;
            /** Sections */
            sections: {
                [key: string]: unknown;
            };
            /** Refused */
            refused: boolean;
        };
        /** AuthUserResponse */
        AuthUserResponse: {
            user: components["schemas"]["UserOut"];
        };
        /** ClarifyOptionOut */
        ClarifyOptionOut: {
            /** Label */
            label: string;
            /** Query */
            query: string;
            /** Filters */
            filters?: {
                [key: string]: unknown;
            } | null;
        };
        /** FeedbackRequest */
        FeedbackRequest: {
            /** Audit Id */
            audit_id: number;
            /** Rating */
            rating: number;
            /** Comment */
            comment?: string | null;
        };
        /** FeedbackResponse */
        FeedbackResponse: {
            /** Audit Id */
            audit_id: number;
            /** Rating */
            rating: number;
            /** Comment */
            comment?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoginRequest */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** ProductCreate */
        ProductCreate: {
            /** Active Ingredient */
            active_ingredient: string;
            /** Dosage Form */
            dosage_form?: string | null;
            /** Route */
            route?: string | null;
            /** Rld Name */
            rld_name?: string | null;
            /** Rld Application Number */
            rld_application_number?: string | null;
            /** Company Status */
            company_status?: string | null;
            /**
             * Source
             * @description one of ['anda_letter', 'drugsfda', 'manual']
             */
            source: string;
            /** Source Url */
            source_url?: string | null;
        };
        /** QueryCitation */
        QueryCitation: {
            /** Short Name */
            short_name: string;
            /** Page */
            page: number;
            /** Chunk Id */
            chunk_id: string;
            /** Doc Id */
            doc_id: number;
            /** Version Id */
            version_id: number;
            /** Source Url */
            source_url: string;
            /** Snippet */
            snippet: string;
        };
        /** QueryRequest */
        QueryRequest: {
            /** Question */
            question: string;
            /** Filters */
            filters?: {
                [key: string]: unknown;
            } | null;
            /** K */
            k?: number | null;
            /** Session Id */
            session_id?: string | null;
        };
        /** QueryResponse */
        QueryResponse: {
            /** Answer */
            answer: string;
            /** Citations */
            citations: components["schemas"]["QueryCitation"][];
            /** Refused */
            refused: boolean;
            /** Model Name */
            model_name: string;
            /** Audit Id */
            audit_id: number;
            /** Session Id */
            session_id: string;
            /** Turn Id */
            turn_id: string;
            /**
             * Status
             * @default answer
             * @enum {string}
             */
            status: "answer" | "summary" | "clarify" | "scope_warning" | "meta" | "refused" | "error";
            /** Reason */
            reason?: string | null;
            /** Interpretation */
            interpretation?: string | null;
            /**
             * Clarify
             * @default []
             */
            clarify: components["schemas"]["ClarifyOptionOut"][];
            /**
             * Related
             * @default []
             */
            related: components["schemas"]["ClarifyOptionOut"][];
        };
        /** ResolveRequest */
        ResolveRequest: {
            /** Rld Name */
            rld_name: string;
            /** Application Number */
            application_number: string;
        };
        /**
         * SourceKind
         * @enum {string}
         */
        SourceKind: "psg" | "orange_book" | "drugsfda" | "shortage" | "ndc" | "rems" | "dailymed";
        /** SourceRecordResponse */
        SourceRecordResponse: {
            source: components["schemas"]["SourceKind"];
            /** Title */
            title: string;
            /** Source Url */
            source_url: string;
            /** Identifiers */
            identifiers: {
                [key: string]: string;
            };
            /** Fields */
            fields: {
                [key: string]: unknown;
            };
        };
        /** SourceSearchRequest */
        SourceSearchRequest: {
            /**
             * Query Text
             * @default
             */
            query_text: string;
            /** Active Ingredient */
            active_ingredient?: string | null;
            /** Brand Name */
            brand_name?: string | null;
            /** Application Number */
            application_number?: string | null;
            /** Ndc */
            ndc?: string | null;
            /** Dosage Form */
            dosage_form?: string | null;
            /** Route */
            route?: string | null;
            /**
             * Limit
             * @default 10
             */
            limit: number;
            /** Sources */
            sources?: components["schemas"]["SourceKind"][] | null;
        };
        /** SourceSearchResponse */
        SourceSearchResponse: {
            /** Routed Sources */
            routed_sources: components["schemas"]["SourceKind"][];
            /** Records */
            records: components["schemas"]["SourceRecordResponse"][];
        };
        /** UserOut */
        UserOut: {
            /** Id */
            id: number;
            /** Email */
            email: string;
            /** Display Name */
            display_name: string;
            /** Role */
            role: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * WhitepaperDocxRequest
         * @description Body: the EXACT JSON object a previous POST /whitepaper returned.
         */
        WhitepaperDocxRequest: {
            /** Result */
            result: {
                [key: string]: unknown;
            };
        };
        /** WhitepaperRequest */
        WhitepaperRequest: {
            /** Rld Name */
            rld_name: string;
            /** Application Number */
            application_number: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthUserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                regwatch_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                regwatch_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthUserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    query_query_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                regwatch_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    query_stream_query_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                regwatch_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    feedback_feedback_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                regwatch_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sources_search_sources_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                regwatch_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourceSearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceSearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    assemble_assemble_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                regwatch_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssembleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssembleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    whitepaper_whitepaper_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                regwatch_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WhitepaperRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_resolve_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                regwatch_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    whitepaper_docx_whitepaper_docx_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                regwatch_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WhitepaperDocxRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    watch_latest_watch_latest_get: {
        parameters: {
            query?: {
                since?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: {
                regwatch_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_products_products_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                regwatch_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_product_products_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                regwatch_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sessions_sessions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                regwatch_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: {
                regwatch_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_session_sessions__session_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: {
                regwatch_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_public_settings_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                regwatch_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
