/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/assemble": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Assemble */
        post: operations["assemble_assemble_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/deficiency/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Deficiency Analyze
         * @description Accept a submission PDF, create the run row, schedule the analysis.
         *
         *     The whole body is size-capped and magic-checked while streaming to a temp
         *     file -- never buffered in memory, never trusted from Content-Length. 202 +
         *     run_id; the UI polls GET /deficiency/runs/{id}.
         */
        post: operations["deficiency_analyze_deficiency_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/deficiency/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Deficiency Runs List
         * @description Org-shared runs, newest first (same product decision as white-paper
         *     runs: any authenticated analyst sees every run).
         */
        get: operations["deficiency_runs_list_deficiency_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/deficiency/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Deficiency Run Detail
         * @description One run + its verbatim stored fault report (null until complete).
         *
         *     Uploads only. Studio checks share this table but are private to their
         *     creator, so serving one here would let any analyst read a colleague's
         *     draft by asking the org-shared route for the same id.
         */
        get: operations["deficiency_run_detail_deficiency_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Diagnose the stack: db, pgvector, providers. Superset of {"status": "ok"}.
         *
         *     503 only when the DB or the vector store is unreachable. An empty corpus is
         *     healthy (with a warning) so a fresh stack can boot and the ingest can seed.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Metrics
         * @description Prometheus text-exposition counters derived from the query_log audit table.
         *
         *     Hand-rolled (no prometheus_client dependency): exposes total queries by mode
         *     and the refusal counter. The body is plain text/version-0.0.4.
         *
         *     Access is OPT-IN: open like /health and /ready by default (so a scraper
         *     reaches it without the session cookie), but when METRICS_TOKEN is set the
         *     request must carry `Authorization: Bearer <token>` or this returns 401.
         *     /health and /ready are never gated this way.
         */
        get: operations["metrics_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/psg/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Psg Documents */
        get: operations["psg_documents_psg_documents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/psg/documents/{doc_id}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Psg Document Content
         * @description One PSG as ordered blocks, rebuilt from the text ingest already stored.
         *
         *     No PDF fetch and no parsing happen here: the chunks of the document's
         *     current version are read and reassembled, which is why this is cheap
         *     enough to serve on every open (a PSG averages three chunks).
         */
        get: operations["psg_document_content_psg_documents__doc_id__content_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/psg/documents/{doc_id}/docx": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Psg Document Docx
         * @description The same PSG as a Word download, generated per request and never stored.
         *
         *     Same source and same blocks as the content route, so what an analyst reads
         *     in the studio and what lands in their working folder cannot drift apart.
         */
        get: operations["psg_document_docx_psg_documents__doc_id__docx_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/psg/documents/{doc_id}/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Psg Document Pdf
         * @description Stream one PSG PDF inline: local cache first, else fetch from fda.gov.
         *
         *     The remote branch reuses the crawler's hardened ``download_pdf`` (polite
         *     pause, streamed byte cap, %PDF validation, write-through cache in ingest's
         *     own naming scheme) under a tighter per-request timeout budget. Error
         *     details never include the upstream URL.
         */
        get: operations["psg_document_pdf_psg_documents__doc_id__pdf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        /**
         * Psg Document Pdf Head
         * @description Availability probe for the Studio's PDF pane.
         *
         *     Answers from the DB row plus at most two stat() calls -- never fda.gov,
         *     never the rate budget -- so the frontend can distinguish "this document
         *     can be served" from a transport failure before mounting the iframe.
         *     FastAPI does not auto-answer HEAD for GET routes, so this handler is
         *     load-bearing, not decoration.
         */
        head: operations["psg_document_pdf_head_psg_documents__doc_id__pdf_head"];
        patch?: never;
        trace?: never;
    };
    "/psg/documents/{doc_id}/requirements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Psg Document Requirements
         * @description The BE requirements ingest extracted from this PSG's current version.
         *
         *     These are not compliance findings about the document: a PSG has no
         *     defects to report. They are what the guidance asks an applicant to do,
         *     each carrying the page and the verbatim quote it came from, so the studio
         *     can anchor them in the rendered text instead of restating them loose.
         */
        get: operations["psg_document_requirements_psg_documents__doc_id__requirements_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Query */
        post: operations["query_query_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/query/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Query Stream
         * @description Streaming twin of POST /query (Server-Sent Events).
         *
         *     Same auth, rate limit, ownership, pipeline, and single audit row as /query;
         *     it streams live progress as ``status`` frames and the SAME validated
         *     QueryResponse as one terminal ``result`` frame (both built via
         *     _build_query_response, so the shapes cannot drift). The Ask UI consumes this
         *     and transparently falls back to POST /query if the stream fails. Rate-limit
         *     (429), ownership (404), and auth (401) are enforced BEFORE the stream opens,
         *     as real HTTP statuses -- never mid-stream.
         */
        post: operations["query_stream_query_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ready
         * @description Readiness probe: 200 only when the DB + vector store are reachable AND the
         *     LLM client is constructable (key present). Distinct from /health's liveness:
         *     a load balancer routes traffic on this. No paid LLM call is made - only the
         *     cheap reachability checks. Both are timeout-bounded by the per-connection
         *     connect/statement timeouts on the shared engine (the vector-store probe is a
         *     `SELECT count(*)` in pgvector mode, so a degraded DB is capped by
         *     DB_STATEMENT_TIMEOUT rather than hanging the probe). 503 names the FIRST
         *     failed check so an operator sees what to fix.
         *
         *     Also fails CLOSED on row level security: boot deliberately tolerates a
         *     lock-contended `ALTER ... ENABLE ROW LEVEL SECURITY` (the 2026-06-18
         *     incident design), so this is where a still-unprotected public table -- which
         *     is readable over a PostgREST-style Data API -- stops being SILENT. No
         *     extra DB round trip: the set is what the boot sweep recorded.
         */
        get: operations["ready_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resolve
         * @description Resolve an RLD name + application number to the canonical spine.
         *
         *     Deterministic entity resolution, NOT an LLM turn: it writes NO audit row
         *     (success or failure) and returns no answer text -- it lets a surface pin a
         *     canonical product without running a full populate. On an unresolved or
         *     mismatched application it 422s with the resolver's own detail (refuse over
         *     guess). Rate-limited like /query, /assemble, /whitepaper (it hits live FDA
         *     sources just as they do).
         */
        post: operations["resolve_resolve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sources Search */
        post: operations["sources_search_sources_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/studio/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Studio Check
         * @description Check one Studio document for candidate deficiencies.
         *
         *     202 + run_id; the UI polls GET /studio/check/{id}. The document is hashed
         *     from the text that will actually be checked, so two checks of an unedited
         *     draft are comparable and an edit is visibly a different document.
         */
        post: operations["studio_check_studio_check_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/studio/check/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Studio Check Detail
         * @description One of the caller's own checks + its verbatim stored report.
         */
        get: operations["studio_check_detail_studio_check__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/watch/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Watch Latest */
        get: operations["watch_latest_watch_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/whitepaper": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Whitepaper
         * @description Populate the CRA White Paper for an RLD name + NDA/ANDA number.
         *
         *     Writes one whitepaper audit row (in build_whitepaper) on success AND on a
         *     422 resolution failure. Rate-limited like /query and /assemble. A
         *     successful populate is persisted as a durable org-shared run and the
         *     response gains ``run_id`` (null when the persist degraded, see
         *     ``_persist_whitepaper_run``).
         */
        post: operations["whitepaper_whitepaper_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/whitepaper/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Whitepaper Runs List
         * @description Org-shared saved runs, newest activity first.
         *
         *     Any authenticated analyst sees every run (a product decision, design doc
         *     section 10); deletes stay creator-only. Shape follows /watch/latest:
         *     count/total/limit/offset so pagination stays truthful.
         */
        get: operations["whitepaper_runs_list_whitepaper_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/whitepaper/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Whitepaper Run Detail
         * @description One saved run: verbatim generated payload + the analyst overlay.
         *
         *     404 for a missing id -- runs are org-shared, so existence is not a secret
         *     (the legacy uniform-422 pattern applied only to the per-user audit lookup).
         */
        get: operations["whitepaper_run_detail_whitepaper_runs__run_id__get"];
        put?: never;
        post?: never;
        /**
         * Whitepaper Run Delete
         * @description Creator-only (403), drafts-only (409): a finalized paper is a record.
         */
        delete: operations["whitepaper_run_delete_whitepaper_runs__run_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/whitepaper/runs/{run_id}/cells/{cell_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Whitepaper Run Set Cell
         * @description Set (or clear) one attributed analyst overlay cell (org-shared edit).
         *
         *     A ``null`` or empty-after-cleaning value clears the cell. No query rate
         *     limit: a pure bounded DB write, no FDA/LLM call. The store owns the domain
         *     rules; this boundary maps its typed errors -- 404 missing run, 409
         *     final-frozen or lost-the-concurrent-insert (retry), 422 unknown cell /
         *     oversized value.
         */
        post: operations["whitepaper_run_set_cell_whitepaper_runs__run_id__cells__cell_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/whitepaper/runs/{run_id}/docx": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Whitepaper Run Docx
         * @description Render the Word document FROM the saved run -- no client echo, no re-populate.
         *
         *     Zero live fetches, zero LLM calls: the .docx renders the STORED generated
         *     layer after re-verifying ``result_fingerprint(sections) == sections_sha256``
         *     (a mismatch is stored-data corruption: 500 + Sentry, no document), with the
         *     attributed analyst overlay applied per the writer's INV-3 discipline. The
         *     official template is lazily fetched on first use (ensure_template); any
         *     fetch failure keeps the loud FALLBACK_MARKER path. Keeps the /query rate
         *     limiter (docx assembly is CPU-bound) and writes one lightweight audit row
         *     (mode="whitepaper", docx_rendered).
         */
        post: operations["whitepaper_run_docx_whitepaper_runs__run_id__docx_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/whitepaper/runs/{run_id}/finalize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Whitepaper Run Finalize
         * @description draft -> final: freezes the analyst layer; open to any analyst, audited.
         *
         *     The store re-verifies the stored sections fingerprint FIRST -- a mismatch
         *     is stored-data corruption (500 + Sentry), never a client error.
         */
        post: operations["whitepaper_run_finalize_whitepaper_runs__run_id__finalize_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/whitepaper/runs/{run_id}/reopen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Whitepaper Run Reopen
         * @description final -> draft: clears the finalize stamp; open to any analyst, audited.
         */
        post: operations["whitepaper_run_reopen_whitepaper_runs__run_id__reopen_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AlertRecord
         * @description One durable alert as ``latest_digest_records`` returns it (the Alert
         *     dataclass fields plus the read-time-derived ``change_kind``).
         */
        AlertRecord: {
            /** Active Ingredient */
            active_ingredient: string;
            /** Captured At */
            captured_at: string;
            /** Change Kind */
            change_kind?: ("new" | "revised") | null;
            /** Confidence */
            confidence: number;
            /** Diff Summary */
            diff_summary: string | null;
            /** Listing Appl No */
            listing_appl_no: string;
            /** Listing Psg Type */
            listing_psg_type: string;
            /** Product Id */
            product_id: number;
            /** Psg Document Id */
            psg_document_id: number;
            /** Psg Version Id */
            psg_version_id: number;
            /** Rationale */
            rationale: string;
            /** Source Url */
            source_url: string;
        };
        /** AssembleRequest */
        AssembleRequest: {
            /** Active Ingredient */
            active_ingredient: string;
            /** Dosage Form */
            dosage_form?: string | null;
            /**
             * Rld
             * @description RLD brand name or application number
             */
            rld?: string | null;
        };
        /** AssembleResponse */
        AssembleResponse: {
            /** Markdown */
            markdown: string;
            /** Refused */
            refused: boolean;
            /** Sections */
            sections: {
                [key: string]: unknown;
            };
        };
        /** Body_deficiency_analyze_deficiency_analyze_post */
        Body_deficiency_analyze_deficiency_analyze_post: {
            /** File */
            file: string;
        };
        /** ClarifyOptionOut */
        ClarifyOptionOut: {
            /** Filters */
            filters?: {
                [key: string]: unknown;
            } | null;
            /** Label */
            label: string;
            /** Query */
            query: string;
        };
        /** DeficiencyAnalyzeResponse */
        DeficiencyAnalyzeResponse: {
            /** Run Id */
            run_id: number;
            /** Status */
            status: string;
        };
        /**
         * DeficiencyRunDetailResponse
         * @description ``report`` is a deliberately passthrough dict: the response must be
         *     VERBATIM what the audited run stored (same discipline as the white-paper
         *     detail route). Null unless the run is complete.
         */
        DeficiencyRunDetailResponse: {
            /** Completed At */
            completed_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Error */
            error: string | null;
            /** Fault Count */
            fault_count: number | null;
            /** Filename */
            filename: string;
            /** Id */
            id: number;
            /** Page Count */
            page_count: number | null;
            /** Report */
            report: {
                [key: string]: unknown;
            } | null;
            /** Status */
            status: string;
        };
        /** DeficiencyRunListResponse */
        DeficiencyRunListResponse: {
            /** Count */
            count: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Runs */
            runs: components["schemas"]["DeficiencyRunSummary"][];
            /** Total */
            total: number;
        };
        /**
         * DeficiencyRunSummary
         * @description One run list row. ``status``/``error`` are the READ-TIME interpretation
         *     (``effective_status``): a row stranded pending/running by a process restart
         *     reads as failed after the stale cutoff instead of spinning forever.
         */
        DeficiencyRunSummary: {
            /** Completed At */
            completed_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Error */
            error: string | null;
            /** Fault Count */
            fault_count: number | null;
            /** Filename */
            filename: string;
            /** Id */
            id: number;
            /** Page Count */
            page_count: number | null;
            /** Status */
            status: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthComponents */
        HealthComponents: {
            db: components["schemas"]["HealthDbComponent"];
            embedding: components["schemas"]["HealthEmbeddingComponent"];
            llm: components["schemas"]["HealthLlmComponent"];
            vector_store: components["schemas"]["HealthVectorComponent"];
        };
        /** HealthDbComponent */
        HealthDbComponent: {
            /** Dialect */
            dialect?: string | null;
            /** Error */
            error?: string | null;
            /** Ok */
            ok: boolean;
        };
        /** HealthEmbeddingComponent */
        HealthEmbeddingComponent: {
            /** Profile */
            profile: string;
            /** Provider */
            provider: string;
        };
        /** HealthLlmComponent */
        HealthLlmComponent: {
            /** Key Present */
            key_present: boolean;
            /** Provider */
            provider: string;
        };
        /** HealthResponse */
        HealthResponse: {
            /** Allow Test Providers */
            allow_test_providers?: boolean | null;
            components: components["schemas"]["HealthComponents"];
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "unhealthy";
            /** Warnings */
            warnings: string[];
            /**
             * Whitepaper Template
             * @enum {string}
             */
            whitepaper_template: "present" | "fetchable" | "absent";
        };
        /** HealthVectorComponent */
        HealthVectorComponent: {
            /** Corpus Count */
            corpus_count?: number | null;
            /** Error */
            error?: string | null;
            /** Ok */
            ok: boolean;
        };
        /**
         * PsgContentBlock
         * @description One block of a reference PSG, in the studio's own block vocabulary.
         */
        PsgContentBlock: {
            /** Id */
            id: string;
            /** Page */
            page: number;
            /** Text */
            text: string;
            /**
             * Type
             * @enum {string}
             */
            type: "title" | "meta" | "h2" | "p";
        };
        /**
         * PsgDocumentContentResponse
         * @description One PSG rendered as a document the studio can open like a working file.
         *
         *     ``file_name`` carries the .docx name the rail shows and the download
         *     produces, so the client never builds a second one that could disagree.
         *     ``truncated`` is surfaced rather than swallowed: a short body with no
         *     explanation would read as a short guidance.
         */
        PsgDocumentContentResponse: {
            /** Active Ingredient */
            active_ingredient: string;
            /** Appl No */
            appl_no: string | null;
            /** Blocks */
            blocks: components["schemas"]["PsgContentBlock"][];
            /** Dosage Form */
            dosage_form: string | null;
            /** File Name */
            file_name: string;
            /** Id */
            id: number;
            /** Page Count */
            page_count: number;
            /** Psg Type */
            psg_type: string;
            /** Recommended Date */
            recommended_date: string | null;
            /** Route */
            route: string | null;
            /** Source Url */
            source_url: string;
            /** Truncated */
            truncated: boolean;
        };
        /** PsgDocumentListResponse */
        PsgDocumentListResponse: {
            /** Count */
            count: number;
            /** Documents */
            documents: components["schemas"]["PsgLibraryDoc"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /**
         * PsgLibraryDoc
         * @description One psg_document catalog row for the reference-library rail.
         *
         *     ``stripped_name`` is derived at read time (text_normalize.stripped_name) so
         *     the client can salt-collapse ("albuterol sulfate" -> "albuterol") without
         *     shipping the salt-token table. ``psg_type`` stays a plain str (house
         *     precedent: AlertRecord's listing fields) -- the crawler only ever writes
         *     "draft"/"final", and a str never 500s on a legacy row.
         */
        PsgLibraryDoc: {
            /** Active Ingredient */
            active_ingredient: string;
            /** Appl No */
            appl_no: string | null;
            /** Dosage Form */
            dosage_form: string | null;
            /** Id */
            id: number;
            /** Normalized Name */
            normalized_name: string;
            /** Psg Type */
            psg_type: string;
            /** Recommended Date */
            recommended_date: string | null;
            /** Route */
            route: string | null;
            /** Source Url */
            source_url: string;
            /** Stripped Name */
            stripped_name: string;
        };
        /**
         * PsgRequirementOut
         * @description One extracted requirement, with the FDA words it was taken from.
         */
        PsgRequirementOut: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Page */
            page: number | null;
            /** Quote */
            quote: string | null;
            /** Value */
            value: string;
        };
        /**
         * PsgRequirementsResponse
         * @description What one PSG requires of an ANDA, as ingest extracted it.
         *
         *     ``extracted`` is False when no extraction row exists for this version
         *     (the ``--no-extract`` ingest path). The client must say so rather than
         *     render an empty list as "this guidance requires nothing" -- the two are
         *     opposite claims.
         */
        PsgRequirementsResponse: {
            /** Extracted */
            extracted: boolean;
            /** Id */
            id: number;
            /** Requirements */
            requirements: components["schemas"]["PsgRequirementOut"][];
        };
        /** QueryCitation */
        QueryCitation: {
            /** Chunk Id */
            chunk_id: string;
            /** Diff Summary */
            diff_summary?: string | null;
            /** Doc Id */
            doc_id: number;
            /** Dosage Form */
            dosage_form?: string | null;
            /** Page */
            page: number;
            /** Product Name */
            product_name?: string | null;
            /** Psg Type */
            psg_type?: string | null;
            /** Recommended Date */
            recommended_date?: string | null;
            /** Route */
            route?: string | null;
            /** Score */
            score?: number | null;
            /** Short Name */
            short_name: string;
            /** Snippet */
            snippet: string;
            /** Source Url */
            source_url: string;
            /** Version Id */
            version_id: number;
        };
        /** QueryRequest */
        QueryRequest: {
            /** Filters */
            filters?: {
                [key: string]: unknown;
            } | null;
            /** K */
            k?: number | null;
            /**
             * Live Draft
             * @default false
             */
            live_draft: boolean;
            /**
             * Origin
             * @default thread
             * @enum {string}
             */
            origin: "thread" | "assistant";
            /** Question */
            question: string;
            /** Session Id */
            session_id?: string | null;
        };
        /** QueryResponse */
        QueryResponse: {
            /** Answer */
            answer: string;
            /** Audit Id */
            audit_id: number;
            /** Citations */
            citations: components["schemas"]["QueryCitation"][];
            /**
             * Clarify
             * @default []
             */
            clarify: components["schemas"]["ClarifyOptionOut"][];
            /** Draft Withdrawn */
            draft_withdrawn?: string | null;
            /** Interpretation */
            interpretation?: string | null;
            /** Model Name */
            model_name: string;
            /** Reason */
            reason?: string | null;
            /** Refused */
            refused: boolean;
            /**
             * Related
             * @default []
             */
            related: components["schemas"]["ClarifyOptionOut"][];
            /** Session Id */
            session_id: string;
            /**
             * Status
             * @default answer
             * @enum {string}
             */
            status: "answer" | "summary" | "clarify" | "scope_warning" | "meta" | "refused" | "error";
            /** Turn Id */
            turn_id: string;
        };
        /** ReadyChecks */
        ReadyChecks: {
            /** Db */
            db: boolean;
            /** Llm */
            llm: boolean;
            /** Rls */
            rls?: boolean | null;
            /** Vector Store */
            vector_store: boolean;
        };
        /** ReadyResponse */
        ReadyResponse: {
            checks: components["schemas"]["ReadyChecks"];
            /** Detail */
            detail?: string | null;
            /** Failed */
            failed?: ("db" | "vector_store" | "llm" | "rls") | null;
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "not_ready";
        };
        /** ResolveRequest */
        ResolveRequest: {
            /** Application Number */
            application_number: string;
            /** Rld Name */
            rld_name: string;
        };
        /**
         * SourceKind
         * @enum {string}
         */
        SourceKind: "psg" | "orange_book" | "drugsfda" | "shortage" | "ndc" | "rems" | "dailymed";
        /** SourceRecordResponse */
        SourceRecordResponse: {
            /** Fields */
            fields: {
                [key: string]: unknown;
            };
            /** Identifiers */
            identifiers: {
                [key: string]: string;
            };
            source: components["schemas"]["SourceKind"];
            /** Source Url */
            source_url: string;
            /** Title */
            title: string;
        };
        /** SourceSearchRequest */
        SourceSearchRequest: {
            /** Active Ingredient */
            active_ingredient?: string | null;
            /** Application Number */
            application_number?: string | null;
            /** Brand Name */
            brand_name?: string | null;
            /** Dosage Form */
            dosage_form?: string | null;
            /**
             * Limit
             * @default 10
             */
            limit: number;
            /** Ndc */
            ndc?: string | null;
            /**
             * Query Text
             * @default
             */
            query_text: string;
            /** Route */
            route?: string | null;
            /** Sources */
            sources?: components["schemas"]["SourceKind"][] | null;
        };
        /** SourceSearchResponse */
        SourceSearchResponse: {
            /** Records */
            records: components["schemas"]["SourceRecordResponse"][];
            /** Routed Sources */
            routed_sources: components["schemas"]["SourceKind"][];
        };
        /**
         * StudioBlockIn
         * @description One editable block of a Studio document, as the canvas holds it.
         */
        StudioBlockIn: {
            /** Id */
            id: string;
            /** Rows */
            rows?: components["schemas"]["StudioRowIn"][] | null;
            /** Text */
            text: string;
            /** Type */
            type: string;
        };
        /** StudioCheckRequest */
        StudioCheckRequest: {
            /** Blocks */
            blocks: components["schemas"]["StudioBlockIn"][];
            /** Name */
            name: string;
        };
        /**
         * StudioRowIn
         * @description One row of a Studio table block.
         */
        StudioRowIn: {
            /** Cells */
            cells?: string[];
            /**
             * Head
             * @default false
             */
            head: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WatchLatestResponse */
        WatchLatestResponse: {
            /** Alerts */
            alerts: components["schemas"]["AlertRecord"][];
            /** Count */
            count: number;
            last_run: components["schemas"]["WatchRunSummary"] | null;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /**
         * WatchRunSummary
         * @description Telemetry of the newest COMPLETED watch run (the durable ledger row).
         */
        WatchRunSummary: {
            /** Added */
            added: number;
            /** Alerts */
            alerts: number;
            /** Errors */
            errors: number;
            /** Finished At */
            finished_at: string;
            /** Listings */
            listings: number;
            /** Matched */
            matched: number;
            /** Revised */
            revised: number;
            /** Started At */
            started_at: string;
            /** Unchanged */
            unchanged: number;
        };
        /** WhitepaperCellRequest */
        WhitepaperCellRequest: {
            /** Value */
            value?: string | null;
        };
        /** WhitepaperCellResponse */
        WhitepaperCellResponse: {
            /** Cell Id */
            cell_id: string;
            /** Cleared */
            cleared: boolean;
            input: components["schemas"]["WhitepaperInputOut"] | null;
            /** Run Id */
            run_id: number;
        };
        /**
         * WhitepaperInputOut
         * @description One attributed analyst overlay value.
         */
        WhitepaperInputOut: {
            /** Author */
            author: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Value */
            value: string;
        };
        /** WhitepaperRequest */
        WhitepaperRequest: {
            /** Application Number */
            application_number: string;
            /** Rld Name */
            rld_name: string;
        };
        /**
         * WhitepaperResponse
         * @description The populate result, verbatim.
         *
         *     ``spine``/``sections`` are deliberately passthrough (plain dict/list, no
         *     nested models) for the same INV-3 reason as WhitepaperRunDetailResponse:
         *     ``_persist_whitepaper_run`` stores this exact payload BEFORE serialization,
         *     so a typed model that stripped or reshaped a field would make the stored
         *     run diverge from the HTTP response (tests pin the parity).
         */
        WhitepaperResponse: {
            /** Audit Id */
            audit_id: number;
            /** Run Id */
            run_id: number | null;
            /** Sections */
            sections: {
                [key: string]: unknown;
            }[];
            /** Spine */
            spine: {
                [key: string]: unknown;
            };
            /** Warnings */
            warnings: string[];
        };
        /** WhitepaperRunDeleteResponse */
        WhitepaperRunDeleteResponse: {
            /** Deleted */
            deleted: boolean;
            /** Run Id */
            run_id: number;
        };
        /**
         * WhitepaperRunDetailResponse
         * @description The full stored run.
         *
         *     ``spine``/``sections``/``warnings`` are deliberately passthrough fields
         *     (plain dict/list, no nested models): the response must be VERBATIM what the
         *     audited populate stored -- serialization may never reshape or filter the
         *     fingerprinted sections payload (INV-3).
         */
        WhitepaperRunDetailResponse: {
            /** Analyst Input Count */
            analyst_input_count: number;
            /** Application Number */
            application_number: string;
            /** Application Type */
            application_type: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Created By */
            created_by: string;
            /** Created By User Id */
            created_by_user_id: number;
            /** Finalized At */
            finalized_at: string | null;
            /** Finalized By */
            finalized_by: string | null;
            /** Id */
            id: number;
            /** Ingredient */
            ingredient: string;
            /** Inputs */
            inputs: {
                [key: string]: components["schemas"]["WhitepaperInputOut"];
            };
            /** Normalized Name */
            normalized_name: string;
            /** Populated Count */
            populated_count: number;
            /** Rld Name Input */
            rld_name_input: string;
            /** Sections */
            sections: {
                [key: string]: unknown;
            }[];
            /** Source Audit Id */
            source_audit_id: number;
            /** Spine */
            spine: {
                [key: string]: unknown;
            };
            /** Status */
            status: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Verified Absent Count */
            verified_absent_count: number;
            /** Warnings */
            warnings: string[];
        };
        /** WhitepaperRunListResponse */
        WhitepaperRunListResponse: {
            /** Count */
            count: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Runs */
            runs: components["schemas"]["WhitepaperRunSummary"][];
            /** Total */
            total: number;
        };
        /** WhitepaperRunStatusResponse */
        WhitepaperRunStatusResponse: {
            /** Run Id */
            run_id: number;
            /** Status */
            status: string;
        };
        /**
         * WhitepaperRunSummary
         * @description One org-shared run list row (no JSON payloads -- see the detail route).
         */
        WhitepaperRunSummary: {
            /** Analyst Input Count */
            analyst_input_count: number;
            /** Application Number */
            application_number: string;
            /** Application Type */
            application_type: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Created By */
            created_by: string;
            /** Id */
            id: number;
            /** Ingredient */
            ingredient: string;
            /** Inputs Count */
            inputs_count: number;
            /** Normalized Name */
            normalized_name: string;
            /** Populated Count */
            populated_count: number;
            /** Rld Name Input */
            rld_name_input: string;
            /** Status */
            status: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Verified Absent Count */
            verified_absent_count: number;
        };
        /**
         * WhitepaperSpine
         * @description The canonical spine ``populator._spine_from_ctx`` emits.
         *
         *     Typed here (unlike the /whitepaper embedding, which must stay verbatim
         *     passthrough for stored-run parity) because /resolve persists nothing: the
         *     response IS the whole contract. application_type is a code-verified closed
         *     set - every assignment in populator resolves to an NDA/ANDA/BLA prefix.
         */
        WhitepaperSpine: {
            /** Application Number */
            application_number: string;
            /**
             * Application Type
             * @enum {string}
             */
            application_type: "NDA" | "ANDA" | "BLA";
            /** Ingredient */
            ingredient: string;
            /** Normalized Name */
            normalized_name: string;
            /** Product Numbers */
            product_numbers: string[];
            /** Setid */
            setid: string | null;
            /** Spl Candidates */
            spl_candidates: components["schemas"]["WhitepaperSplCandidate"][];
            /** Warnings */
            warnings: string[];
        };
        /** WhitepaperSplCandidate */
        WhitepaperSplCandidate: {
            /** Labeler */
            labeler: string | null;
            /** Published */
            published: string | null;
            /** Setid */
            setid: string;
            /** Title */
            title: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    assemble_assemble_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                regwatch_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssembleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssembleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deficiency_analyze_deficiency_analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                regwatch_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_deficiency_analyze_deficiency_analyze_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeficiencyAnalyzeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deficiency_runs_list_deficiency_runs_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: {
                regwatch_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeficiencyRunListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deficiency_run_detail_deficiency_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: number;
            };
            cookie?: {
                regwatch_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeficiencyRunDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    metrics_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    psg_documents_psg_documents_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: {
                regwatch_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PsgDocumentListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    psg_document_content_psg_documents__doc_id__content_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: number;
            };
            cookie?: {
                regwatch_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PsgDocumentContentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    psg_document_docx_psg_documents__doc_id__docx_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: number;
            };
            cookie?: {
                regwatch_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    psg_document_pdf_psg_documents__doc_id__pdf_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: number;
            };
            cookie?: {
                regwatch_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    psg_document_pdf_head_psg_documents__doc_id__pdf_head: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: number;
            };
            cookie?: {
                regwatch_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    psg_document_requirements_psg_documents__doc_id__requirements_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: number;
            };
            cookie?: {
                regwatch_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PsgRequirementsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    query_query_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                regwatch_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    query_stream_query_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                regwatch_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ready_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyResponse"];
                };
            };
        };
    };
    resolve_resolve_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                regwatch_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WhitepaperSpine"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sources_search_sources_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                regwatch_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourceSearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceSearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    studio_check_studio_check_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                regwatch_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StudioCheckRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeficiencyAnalyzeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    studio_check_detail_studio_check__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: number;
            };
            cookie?: {
                regwatch_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeficiencyRunDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    watch_latest_watch_latest_get: {
        parameters: {
            query?: {
                since?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: {
                regwatch_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchLatestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    whitepaper_whitepaper_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                regwatch_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WhitepaperRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WhitepaperResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    whitepaper_runs_list_whitepaper_runs_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                application_number?: string | null;
                normalized_name?: string | null;
                status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: {
                regwatch_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WhitepaperRunListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    whitepaper_run_detail_whitepaper_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: number;
            };
            cookie?: {
                regwatch_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WhitepaperRunDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    whitepaper_run_delete_whitepaper_runs__run_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: number;
            };
            cookie?: {
                regwatch_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WhitepaperRunDeleteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    whitepaper_run_set_cell_whitepaper_runs__run_id__cells__cell_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: number;
                cell_id: string;
            };
            cookie?: {
                regwatch_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WhitepaperCellRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WhitepaperCellResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    whitepaper_run_docx_whitepaper_runs__run_id__docx_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: number;
            };
            cookie?: {
                regwatch_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    whitepaper_run_finalize_whitepaper_runs__run_id__finalize_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: number;
            };
            cookie?: {
                regwatch_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WhitepaperRunStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    whitepaper_run_reopen_whitepaper_runs__run_id__reopen_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: number;
            };
            cookie?: {
                regwatch_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WhitepaperRunStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
