// Typed client for the RegWatch FastAPI backend.
//
// The /query-family wire types (Citation, ClarifyOption, QueryResponse,
// QueryStatus) are DERIVED from the FastAPI OpenAPI schema in lib/api-types.ts
// (regenerated by `npm run gen:types`; a CI job fails on drift). The remaining
// response types are hand-written: their routes carry no response_model, so
// they are not in the schema — keep them in sync with main.py by hand.
import type { components } from "./api-types";

type Schemas = components["schemas"];

// Resolve the API base at call time. When the page is served from a REMOTE
// origin (e.g. a cloudflared tunnel) we ALWAYS use the same-origin "/api" path
// that next.config.mjs proxies to the backend — a localhost base would point at
// the visitor's own machine, not the server. NEXT_PUBLIC_API_BASE is honored
// only when actually running on localhost (for direct-call local dev).
function apiBase(): string {
  if (typeof window !== "undefined") {
    const host = window.location.hostname;
    if (host !== "localhost" && host !== "127.0.0.1") return "/api";
  }
  const configured = process.env.NEXT_PUBLIC_API_BASE;
  return configured && configured.length > 0 ? configured : "/api";
}

export type Citation = Schemas["QueryCitation"];
export type ClarifyOption = Schemas["ClarifyOptionOut"];
// A grounded clarify pick: tapping it resends {query, filters} in-session.
export type Suggestion = ClarifyOption;
export type QueryResponse = Schemas["QueryResponse"];
// "answer" | "summary" | "clarify" | "scope_warning" | "refused" | "error" —
// by construction from the backend Literal. No "conversational".
export type QueryStatus = QueryResponse["status"];

// clarify is the only array the wire may omit (backend default []); guarantee
// it so consumers never branch on undefined. suggestions/unanswered no longer
// exist — the generated type makes referencing them a compile error.
function normalizeQuery(r: QueryResponse): QueryResponse {
  return { ...r, clarify: r.clarify ?? [] };
}

export interface AssembleResponse {
  markdown: string;
  sections: Record<string, unknown>;
  refused: boolean;
}

// --- White Paper populator (POST /whitepaper) -------------------------------
// Cells are tri-state. manual cells are ALWAYS analyst_input_required with
// evidence attached and no generated value; verified_absent means the source
// was queried successfully and the record is genuinely absent (renders "No",
// query recorded in evidence) — a failed or ambiguous lookup never says "No".

export type WhitepaperCellMode = "auto" | "evidence_only" | "manual";
export type WhitepaperCellStatus = "populated" | "analyst_input_required" | "verified_absent";

export interface WhitepaperEvidence {
  source: string;
  locator: string;
  source_url: string | null;
  fetched_at: string | null;
  page: number | null;
  section: string | null;
  snippet: string | null;
}

export interface WhitepaperCell {
  id: string;
  label: string;
  mode: WhitepaperCellMode;
  status: WhitepaperCellStatus;
  value: string | null;
  evidence: WhitepaperEvidence[];
  note: string | null;
}

export interface WhitepaperSectionData {
  title: string;
  cells: WhitepaperCell[];
}

export interface WhitepaperSpine {
  application_number: string;
  // The backend can also resolve BLA inputs (Drugs@FDA / Orange Book carry them).
  application_type: "NDA" | "ANDA" | "BLA";
  ingredient: string;
  normalized_name: string;
  product_numbers: string[];
  setid: string | null;
  warnings: string[];
}

export interface WhitepaperResponse {
  spine: WhitepaperSpine;
  sections: WhitepaperSectionData[];
  warnings: string[];
  audit_id: number;
}

export interface AlertRecord {
  product_id: number;
  active_ingredient: string;
  listing_appl_no: string;
  listing_psg_type: string;
  psg_document_id: number;
  psg_version_id: number;
  captured_at: string;
  diff_summary: string | null;
  confidence: number;
  rationale: string;
  source_url: string;
}
export interface WatchLatest {
  count: number;
  alerts: AlertRecord[];
}

export interface ProductRecord {
  id: number | null;
  active_ingredient: string;
  normalized_name: string;
  stripped_name: string;
  dosage_form: string | null;
  route: string | null;
  rld_name: string | null;
  rld_application_number: string | null;
  company_status: string | null;
  source: string;
  source_url: string | null;
}
export interface ProductsResponse {
  count: number;
  products: ProductRecord[];
}

export interface PublicSettings {
  embedding_provider: string;
  llm_provider: string;
  llm_model: string;
  retrieval_top_k: number | null;
  refusal_score_threshold: number;
  company_name: string;
}

export interface User {
  id: number;
  email: string;
  display_name: string;
  role: string;
}

export interface SessionSummary {
  id: string;
  title: string;
  created_at: string;
  updated_at: string;
  message_count: number;
}

// GET /sessions/{id} returns a raw dict (no response_model), so these fields
// aren't in the generated api-types.ts — type them here by hand to match the
// backend serializer (main.py get_session). Tier-2: rehydrated turns now carry
// their provenance (audit_id), refusal/clarify reason, interpretation, and the
// clarify/related next-step affordances, so a reopened conversation is fully
// interactive rather than a dead end.
export interface ChatMessage {
  id: string;
  turn_id: string;
  role: "user" | "assistant";
  content: string;
  status: string | null;
  citations: Citation[];
  audit_id: number | null;
  reason: string | null;
  interpretation: string | null;
  clarify: ClarifyOption[];
  related: ClarifyOption[];
  created_at: string;
}

export interface SessionDetail {
  session: { id: string; title: string; created_at: string; updated_at: string };
  messages: ChatMessage[];
}

export class ApiError extends Error {
  readonly status: number;
  readonly detail: string;
  constructor(status: number, detail: string) {
    super(detail);
    this.name = "ApiError";
    this.status = status;
    this.detail = detail;
  }
}

// AuthProvider registers a callback here, so a 401 from ANY protected call
// (everything except /auth/login) drops client auth state in one place; the
// provider then routes to /login.
let onUnauthorized: (() => void) | null = null;
export function setUnauthorizedHandler(handler: (() => void) | null): void {
  onUnauthorized = handler;
}

async function handle<T>(res: Response, method: string, path: string, gate: boolean): Promise<T> {
  if (res.status === 401 && gate) {
    onUnauthorized?.();
    throw new ApiError(401, "authentication required");
  }
  if (!res.ok) {
    let detail = "";
    try {
      const body = (await res.json()) as { detail?: unknown };
      if (typeof body.detail === "string") detail = body.detail;
    } catch {
      // non-JSON error body
    }
    // 429 surfaces on six expensive routes but the backend detail is the terse
    // "rate limit exceeded"; give every consumer one friendly default so a
    // rate-limited query/assemble/whitepaper/docx reads as guidance, not a code.
    // (login keys its own copy off err.status, so this message doesn't affect it.)
    if (res.status === 429) {
      throw new ApiError(429, "You're sending requests too fast — wait a moment and try again.");
    }
    throw new ApiError(res.status, detail || `${method} ${path} → ${res.status}`);
  }
  if (res.status === 204) {
    return undefined as unknown as T;
  }
  return res.json() as Promise<T>;
}

// credentials: "include" — auth rides in the HttpOnly session cookie. The
// same-origin /api proxy would include it by default, but the direct-call dev
// mode (NEXT_PUBLIC_API_BASE on localhost) is cross-origin and would silently
// drop the cookie without this; the backend's CORS allows credentials.
async function postJSON<T>(path: string, body: unknown, gate = true, signal?: AbortSignal): Promise<T> {
  const res = await fetch(`${apiBase()}${path}`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(body),
    credentials: "include",
    signal,
  });
  return handle<T>(res, "POST", path, gate);
}

async function getJSON<T>(path: string): Promise<T> {
  const res = await fetch(`${apiBase()}${path}`, { credentials: "include" });
  return handle<T>(res, "GET", path, true);
}

async function deleteJSON(path: string): Promise<void> {
  const res = await fetch(`${apiBase()}${path}`, { method: "DELETE", credentials: "include" });
  await handle<void>(res, "DELETE", path, true);
}

export async function login(email: string, password: string): Promise<User> {
  // gate=false: a 401 here means bad credentials, not an expired session.
  const data = await postJSON<{ user: User }>("/auth/login", { email, password }, false);
  return data.user;
}

export async function logout(): Promise<void> {
  const res = await fetch(`${apiBase()}/auth/logout`, {
    method: "POST",
    credentials: "include",
  });
  await handle<void>(res, "POST", "/auth/logout", false);
}

export async function me(): Promise<User> {
  const data = await getJSON<{ user: User }>("/auth/me");
  return data.user;
}

export function listSessions(): Promise<{ sessions: SessionSummary[] }> {
  return getJSON<{ sessions: SessionSummary[] }>("/sessions");
}

export function getSession(sessionId: string): Promise<SessionDetail> {
  return getJSON<SessionDetail>(`/sessions/${encodeURIComponent(sessionId)}`);
}

export function deleteSession(sessionId: string): Promise<void> {
  return deleteJSON(`/sessions/${encodeURIComponent(sessionId)}`);
}

export async function askQuery(
  question: string,
  filters: Record<string, string> | null = null,
  session_id: string | null = null,
  signal?: AbortSignal,
): Promise<QueryResponse> {
  return normalizeQuery(await postJSON<QueryResponse>("/query", { question, filters, session_id }, true, signal));
}

function isAbortError(e: unknown): boolean {
  return e instanceof Error && e.name === "AbortError";
}

// Minimal text/event-stream reader for /query/stream. Frames per the pinned
// contract: zero or more `event: status` / `data: {"text": …}` then exactly
// one `event: result` whose data is the full QueryResponse, then close.
// Returns null if the stream closes without a result frame (caller falls
// back to plain /query).
async function consumeSse(
  body: ReadableStream<Uint8Array>,
  onStatus?: (text: string) => void,
): Promise<QueryResponse | null> {
  const reader = body.getReader();
  const decoder = new TextDecoder();
  let buf = "";
  let eventName = "";
  let data = "";

  const dispatch = (): QueryResponse | null => {
    const name = eventName;
    const payload = data;
    eventName = "";
    data = "";
    if (!payload) return null;
    if (name === "status") {
      try {
        const d = JSON.parse(payload) as { text?: unknown };
        if (typeof d.text === "string") onStatus?.(d.text);
      } catch {
        // a malformed status frame is cosmetic — keep reading
      }
      return null;
    }
    if (name === "result") return JSON.parse(payload) as QueryResponse;
    return null;
  };

  try {
    for (;;) {
      const { done, value } = await reader.read();
      if (done) break;
      buf += decoder.decode(value, { stream: true });
      let nl: number;
      while ((nl = buf.indexOf("\n")) !== -1) {
        let line = buf.slice(0, nl);
        buf = buf.slice(nl + 1);
        if (line.endsWith("\r")) line = line.slice(0, -1);
        if (line === "") {
          const result = dispatch();
          if (result) return result;
          continue;
        }
        if (line.startsWith(":")) continue; // SSE comment / keep-alive
        const colon = line.indexOf(":");
        const field = colon === -1 ? line : line.slice(0, colon);
        let value2 = colon === -1 ? "" : line.slice(colon + 1);
        if (value2.startsWith(" ")) value2 = value2.slice(1);
        if (field === "event") eventName = value2;
        else if (field === "data") data = data ? `${data}\n${value2}` : value2;
        // id:/retry: are irrelevant here
      }
    }
    // Stream closed. Flush any bytes still held in the decoder, then drain a
    // residual final line (a frame whose last line carried no trailing newline
    // — otherwise its data would be lost and the question re-sent on fallback).
    buf += decoder.decode();
    let tail = buf;
    if (tail.endsWith("\r")) tail = tail.slice(0, -1);
    if (tail !== "" && !tail.startsWith(":")) {
      const colon = tail.indexOf(":");
      const field = colon === -1 ? tail : tail.slice(0, colon);
      let value2 = colon === -1 ? "" : tail.slice(colon + 1);
      if (value2.startsWith(" ")) value2 = value2.slice(1);
      if (field === "event") eventName = value2;
      else if (field === "data") data = data ? `${data}\n${value2}` : value2;
    }
    // A trailing record without its blank-line terminator still dispatches.
    return dispatch();
  } finally {
    void reader.cancel().catch(() => {});
  }
}

// Streamed ask. Status frames arrive via onStatus while the backend works;
// resolves with the same QueryResponse shape as askQuery. Any stream-level
// failure (endpoint missing, proxy buffering, mid-stream error, stream closed
// without a result frame) falls back to plain POST /query transparently — the
// pinned contract accepts that a mid-stream fallback re-runs the question.
// An abort (new chat / session switch) is NOT a failure: it rethrows so the
// caller can discard the turn instead of double-sending.
export async function askQueryStream(
  question: string,
  filters: Record<string, string> | null = null,
  session_id: string | null = null,
  onStatus?: (text: string) => void,
  signal?: AbortSignal,
): Promise<QueryResponse> {
  const path = "/query/stream";
  let res: Response;
  try {
    res = await fetch(`${apiBase()}${path}`, {
      method: "POST",
      headers: { "Content-Type": "application/json", Accept: "text/event-stream" },
      body: JSON.stringify({ question, filters, session_id }),
      credentials: "include",
      signal,
    });
  } catch (e) {
    if (isAbortError(e)) throw e;
    return askQuery(question, filters, session_id, signal);
  }
  if (res.status === 401) {
    onUnauthorized?.();
    throw new ApiError(401, "authentication required");
  }
  const contentType = (res.headers.get("content-type") ?? "").toLowerCase();
  if (!res.ok || !res.body || !contentType.includes("text/event-stream")) {
    // 404/405 (endpoint not deployed yet) or a non-streaming response. Cancel
    // the body so a stray non-SSE stream can't run alongside the fallback.
    void res.body?.cancel().catch(() => {});
    return askQuery(question, filters, session_id, signal);
  }
  try {
    const result = await consumeSse(res.body, onStatus);
    if (result) return normalizeQuery(result);
  } catch (e) {
    if (isAbortError(e)) throw e;
    // fall through to the plain call
  }
  if (signal?.aborted) throw new DOMException("aborted", "AbortError");
  return askQuery(question, filters, session_id, signal);
}

export function assemble(
  active_ingredient: string,
  dosage_form: string | null = null,
  rld: string | null = null,
): Promise<AssembleResponse> {
  return postJSON<AssembleResponse>("/assemble", { active_ingredient, dosage_form, rld });
}

export function buildWhitepaper(
  rldName: string,
  applicationNumber: string,
): Promise<WhitepaperResponse> {
  // A 422 here is the resolution-failure contract: detail explains what WAS
  // found — surface it verbatim, never retry with a guess.
  return postJSON<WhitepaperResponse>("/whitepaper", {
    rld_name: rldName,
    application_number: applicationNumber,
  });
}

// Validate an RLD name + application number into the canonical spine, without
// running a populate. Deterministic entity resolution — the backend writes no
// audit row and returns no answer text. Same 422 contract as buildWhitepaper:
// `detail` explains what WAS found; postJSON surfaces it as an ApiError, never
// a guess. Returns the bare spine.
export function resolveProduct(
  rldName: string,
  applicationNumber: string,
): Promise<WhitepaperSpine> {
  return postJSON<WhitepaperSpine>("/resolve", {
    rld_name: rldName,
    application_number: applicationNumber,
  });
}

// Content-Disposition: attachment; filename=whitepaper_020503.docx — also
// tolerates the quoted and RFC 5987 (filename*=UTF-8''…) forms.
function filenameFromDisposition(header: string | null): string | null {
  if (!header) return null;
  const star = /filename\*\s*=\s*(?:UTF-8'')?([^;]+)/i.exec(header);
  if (star) {
    try {
      return decodeURIComponent(star[1].trim().replace(/^"+|"+$/g, ""));
    } catch {
      // malformed encoding — fall through to the plain form
    }
  }
  const plain = /filename\s*=\s*"?([^";]+)"?/i.exec(header);
  return plain ? plain[1].trim() : null;
}

// The body is {result: <the exact JSON object buildWhitepaper returned>}: the
// server verifies result.audit_id is the caller's own white-paper run and
// renders the .docx FROM that payload — no re-populate, so the document can
// never silently differ from what the analyst reviewed. The 200 is the .docx
// itself: read it as a blob and hand it to the browser as a download under
// the server's Content-Disposition filename. Error bodies are JSON, so they
// go through the shared handler — same 401 gate and detail parsing as every
// other call.
export async function downloadWhitepaperDocx(result: WhitepaperResponse): Promise<void> {
  const path = "/whitepaper/docx";
  const res = await fetch(`${apiBase()}${path}`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ result }),
    credentials: "include",
  });
  if (!res.ok) {
    await handle<never>(res, "POST", path, true); // always throws
    return;
  }
  const blob = await res.blob();
  const fallback = `whitepaper_${result.spine.application_number}.docx`;
  const filename = filenameFromDisposition(res.headers.get("content-disposition")) ?? fallback;
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = filename;
  document.body.appendChild(anchor);
  anchor.click();
  anchor.remove();
  // Revoking in the same tick aborts the download in WebKit — defer until the
  // browser has had a chance to start streaming the blob.
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

// Answer feedback: rating is exactly +1 (helpful) or -1 (not helpful); the
// server upserts per (audit_id, user) so re-rating — or re-sending with a
// comment attached — replaces the previous row rather than stacking. A 404
// means the audit row isn't the caller's own qa answer; surfaced like any
// other ApiError. Response body is ignored on purpose: success is the signal.
export async function sendFeedback(
  auditId: number,
  rating: 1 | -1,
  comment: string | null = null,
): Promise<void> {
  await postJSON<unknown>("/feedback", { audit_id: auditId, rating, comment });
}

export function watchLatest(): Promise<WatchLatest> {
  return getJSON<WatchLatest>("/watch/latest");
}

export function listProducts(): Promise<ProductsResponse> {
  return getJSON<ProductsResponse>("/products");
}

export function getPublicSettings(): Promise<PublicSettings> {
  return getJSON<PublicSettings>("/settings");
}
