// Typed client for the RegWatch FastAPI backend.
//
// Every response type is DERIVED from the FastAPI OpenAPI schema in
// lib/api-types.ts (regenerated by `npm run gen:types`; CI fails on drift of
// either api-types.ts or the committed openapi.json snapshot). The only
// hand-written shapes left are the White-Paper cell/section types, which
// narrow payloads the backend deliberately ships as VERBATIM passthrough
// (INV-3), so they are plain objects in the schema by design.
import type { components } from "./api-types";

type Schemas = components["schemas"];

// Resolve the API base at call time. When the page is served from a REMOTE
// origin (e.g. a cloudflared tunnel) we ALWAYS use the same-origin "/api" path
// that next.config.mjs proxies to the backend — a localhost base would point at
// the visitor's own machine, not the server. NEXT_PUBLIC_API_BASE is honored
// only when actually running on localhost (for direct-call local dev).
function apiBase(): string {
  if (typeof window !== "undefined") {
    const host = window.location.hostname;
    if (host !== "localhost" && host !== "127.0.0.1") return "/api";
  }
  const configured = process.env.NEXT_PUBLIC_API_BASE;
  return configured && configured.length > 0 ? configured : "/api";
}

export type Citation = Schemas["QueryCitation"];
export type ClarifyOption = Schemas["ClarifyOptionOut"];
// A grounded clarify pick: tapping it resends {query, filters} in-session.
export type Suggestion = ClarifyOption;
export type QueryResponse = Schemas["QueryResponse"];
// "answer" | "summary" | "clarify" | "scope_warning" | "refused" | "error" —
// by construction from the backend Literal. No "conversational".
export type QueryStatus = QueryResponse["status"];

// clarify is the only array the wire may omit (backend default []); guarantee
// it so consumers never branch on undefined. suggestions/unanswered no longer
// exist — the generated type makes referencing them a compile error.
function normalizeQuery(r: QueryResponse): QueryResponse {
  return { ...r, clarify: r.clarify ?? [] };
}

export type AssembleResponse = Schemas["AssembleResponse"];

// --- White Paper populator (POST /whitepaper) -------------------------------
// Cells are tri-state. manual cells are ALWAYS analyst_input_required with
// evidence attached and no generated value; verified_absent means the source
// was queried successfully and the record is genuinely absent (renders "No",
// query recorded in evidence) — a failed or ambiguous lookup never says "No".

export type WhitepaperCellMode = "auto" | "evidence_only" | "manual";
export type WhitepaperCellStatus = "populated" | "analyst_input_required" | "verified_absent";

export interface WhitepaperEvidence {
  source: string;
  locator: string;
  source_url: string | null;
  fetched_at: string | null;
  page: number | null;
  section: string | null;
  snippet: string | null;
}

export interface WhitepaperCell {
  id: string;
  label: string;
  mode: WhitepaperCellMode;
  status: WhitepaperCellStatus;
  value: string | null;
  evidence: WhitepaperEvidence[];
  note: string | null;
}

export interface WhitepaperSectionData {
  title: string;
  cells: WhitepaperCell[];
}

// The full DailyMed candidate set behind the setid pick, so the
// repackager-vs-sponsor selection is auditable -- never a silent pick.
export type WhitepaperSplCandidate = Schemas["WhitepaperSplCandidate"];

// The canonical spine (also the whole POST /resolve response body).
export type WhitepaperSpine = Schemas["WhitepaperSpine"];

// POST /whitepaper. spine/sections are VERBATIM passthrough on the wire (the
// persisted run must equal the response, INV-3), so the schema types them as
// plain objects; narrow them to the cell shapes -- the identical payload.
// run_id: the durable org-shared run this populate persisted as. null when
// the persist DEGRADED (populate is the expensive step, so the result still
// ships, with a warning appended) -- the page then renders it inline instead
// of navigating to ?run=.
export type WhitepaperResponse = Omit<Schemas["WhitepaperResponse"], "spine" | "sections"> & {
  spine: WhitepaperSpine;
  sections: WhitepaperSectionData[];
};

// --- White Paper runs (durable, org-shared) ---------------------------------
// These routes carry typed response_models, so the shapes come from the
// generated schema rather than hand-written mirrors.
export type WhitepaperRunSummary = Schemas["WhitepaperRunSummary"];
export type WhitepaperRunList = Schemas["WhitepaperRunListResponse"];
export type WhitepaperInput = Schemas["WhitepaperInputOut"];
export type WhitepaperCellSaved = Schemas["WhitepaperCellResponse"];
export type WhitepaperRunStatus = Schemas["WhitepaperRunStatusResponse"];
// spine/sections are deliberately passthrough on the wire (the stored payload
// is VERBATIM what the audited populate produced, INV-3), so the schema types
// them as plain objects; narrow them here to the same hand-written cell shapes
// the populate response uses -- they are the identical payload.
export type WhitepaperRunDetail = Omit<
  Schemas["WhitepaperRunDetailResponse"],
  "spine" | "sections"
> & {
  spine: WhitepaperSpine;
  sections: WhitepaperSectionData[];
};

// One durable alert off the watch feed. change_kind is the structural
// New-vs-Revised signal, derived server-side from version history; it stays
// optional in the schema so consumers keep their fallback to the "Initial
// version ingested" prose marker under frontend/backend deploy skew.
export type AlertRecord = Schemas["AlertRecord"];
// Telemetry from the most recent completed watch run, straight off the durable
// run ledger. Rendered by the Watch page so "no alerts" can be read honestly:
// an empty feed with a fresh run means "nothing changed", while a stale or
// error-laden run means the feed itself may be wrong. Counters are the run's
// own tallies (INV-4: they report only what that run actually did).
export type WatchRunSummary = Schemas["WatchRunSummary"];
// The feed is a newest-first window (count = page size, total = full matching
// ledger count); last_run is null when no watch run has ever recorded (fresh
// install / wiped ledger) -- the page must say so rather than imply a check
// happened.
export type WatchLatest = Schemas["WatchLatestResponse"];

export type ProductRecord = Schemas["ProductRecord"];
export type ProductsResponse = Schemas["ProductsResponse"];

export type PublicSettings = Schemas["PublicSettings"];

export type User = Schemas["UserOut"];

export type SessionSummary = Schemas["SessionSummary"];

// GET /sessions/{id}. The stored citations/clarify/related payloads are
// VERBATIM passthrough on the wire (legacy sessions carry keys the current
// wire types no longer produce), so the schema types them as plain objects;
// narrow them to the same shapes the live /query wire uses -- rehydrated
// turns keep their provenance (audit_id), refusal/clarify reason,
// interpretation, and the clarify/related next-step affordances, so a
// reopened conversation is fully interactive rather than a dead end. role is
// narrowed the same way: the backend writers only emit user/assistant.
export type ChatMessage = Omit<
  Schemas["ChatMessageOut"],
  "role" | "citations" | "clarify" | "related"
> & {
  role: "user" | "assistant";
  citations: Citation[];
  clarify: ClarifyOption[];
  related: ClarifyOption[];
};

export type SessionDetail = Omit<Schemas["SessionDetailResponse"], "messages"> & {
  messages: ChatMessage[];
};

export class ApiError extends Error {
  readonly status: number;
  readonly detail: string;
  constructor(status: number, detail: string) {
    super(detail);
    this.name = "ApiError";
    this.status = status;
    this.detail = detail;
  }
}

// Request timeouts. Every fetch gets a bound so a hung backend can't leave a
// page spinning forever (it surfaces as a normal ApiError instead). JSON calls
// get a short bound; /query/stream and /whitepaper/docx legitimately take much
// longer (LLM synthesis / .docx render), so they get a longer one.
const DEFAULT_TIMEOUT_MS = 30_000;
const LONG_TIMEOUT_MS = 120_000;
// 504-shaped: a timed-out request never reached a usable response, so the
// closest defined status is "gateway timeout". handle()/login key their UI off
// err.status; this keeps a timeout indistinguishable from a real upstream 504.
const TIMEOUT_STATUS = 504;

// fetch with a hard timeout that is COMPOSED with any caller-supplied signal.
// A fired timeout aborts the request and rejects with an ApiError (so existing
// catch/error UI fires); a caller abort (user-cancel / session switch) still
// propagates as a DOMException("AbortError") so those paths keep working. The
// timer is always cleared, on every path, so it can't leak.
async function fetchWithTimeout(
  input: string,
  init: RequestInit,
  timeoutMs: number,
  callerSignal?: AbortSignal,
): Promise<Response> {
  // A caller signal already aborted before we start: honor it without a fetch.
  if (callerSignal?.aborted) throw new DOMException("aborted", "AbortError");

  const controller = new AbortController();
  let timedOut = false;
  const timer = setTimeout(() => {
    timedOut = true;
    controller.abort();
  }, timeoutMs);

  // Forward a later caller abort onto our controller so user-cancel still
  // aborts the in-flight fetch. Tracked so we can remove the listener on exit.
  const onCallerAbort = () => controller.abort();
  callerSignal?.addEventListener("abort", onCallerAbort, { once: true });

  try {
    return await fetch(input, { ...init, signal: controller.signal });
  } catch (e) {
    // Our controller fired. If it was the timer, surface a defined ApiError;
    // otherwise the caller aborted, so let the AbortError propagate.
    if (timedOut && isAbortError(e)) {
      throw new ApiError(TIMEOUT_STATUS, "The request timed out — please try again.");
    }
    throw e;
  } finally {
    clearTimeout(timer);
    callerSignal?.removeEventListener("abort", onCallerAbort);
  }
}

// AuthProvider registers a callback here, so a 401 from ANY protected call
// (everything except /auth/login) drops client auth state in one place; the
// provider then routes to /login.
let onUnauthorized: (() => void) | null = null;
export function setUnauthorizedHandler(handler: (() => void) | null): void {
  onUnauthorized = handler;
}

async function handle<T>(res: Response, method: string, path: string, gate: boolean): Promise<T> {
  if (res.status === 401 && gate) {
    onUnauthorized?.();
    throw new ApiError(401, "authentication required");
  }
  if (!res.ok) {
    let detail = "";
    try {
      const body = (await res.json()) as { detail?: unknown };
      if (typeof body.detail === "string") detail = body.detail;
      // FastAPI request-validation (422) returns detail as an array of
      // {loc, msg, type}; a field-length reject on /assemble would otherwise
      // read as a bare "POST /assemble → 422". Surface the first message.
      else if (Array.isArray(body.detail)) {
        const first = body.detail[0] as { msg?: unknown } | undefined;
        if (first && typeof first.msg === "string") detail = first.msg;
      }
    } catch {
      // non-JSON error body
    }
    // 429 surfaces on six expensive routes but the backend detail is the terse
    // "rate limit exceeded"; give every consumer one friendly default so a
    // rate-limited query/assemble/whitepaper/docx reads as guidance, not a code.
    // (login keys its own copy off err.status, so this message doesn't affect it.)
    if (res.status === 429) {
      throw new ApiError(429, "You're sending requests too fast — wait a moment and try again.");
    }
    throw new ApiError(res.status, detail || `${method} ${path} → ${res.status}`);
  }
  if (res.status === 204) {
    return undefined as unknown as T;
  }
  return res.json() as Promise<T>;
}

// credentials: "include" — auth rides in the HttpOnly session cookie. The
// same-origin /api proxy would include it by default, but the direct-call dev
// mode (NEXT_PUBLIC_API_BASE on localhost) is cross-origin and would silently
// drop the cookie without this; the backend's CORS allows credentials.
async function postJSON<T>(
  path: string,
  body: unknown,
  gate = true,
  signal?: AbortSignal,
  timeoutMs: number = DEFAULT_TIMEOUT_MS,
): Promise<T> {
  const res = await fetchWithTimeout(
    `${apiBase()}${path}`,
    {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(body),
      credentials: "include",
    },
    timeoutMs,
    signal,
  );
  return handle<T>(res, "POST", path, gate);
}

async function getJSON<T>(path: string): Promise<T> {
  const res = await fetchWithTimeout(
    `${apiBase()}${path}`,
    { credentials: "include" },
    DEFAULT_TIMEOUT_MS,
  );
  return handle<T>(res, "GET", path, true);
}

async function deleteJSON(path: string): Promise<void> {
  const res = await fetchWithTimeout(
    `${apiBase()}${path}`,
    { method: "DELETE", credentials: "include" },
    DEFAULT_TIMEOUT_MS,
  );
  await handle<void>(res, "DELETE", path, true);
}

export async function login(email: string, password: string): Promise<User> {
  // gate=false: a 401 here means bad credentials, not an expired session.
  const data = await postJSON<{ user: User }>("/auth/login", { email, password }, false);
  return data.user;
}

export async function logout(): Promise<void> {
  const res = await fetch(`${apiBase()}/auth/logout`, {
    method: "POST",
    credentials: "include",
  });
  await handle<void>(res, "POST", "/auth/logout", false);
}

export async function me(): Promise<User> {
  const data = await getJSON<{ user: User }>("/auth/me");
  return data.user;
}

export function listSessions(): Promise<{ sessions: SessionSummary[] }> {
  return getJSON<{ sessions: SessionSummary[] }>("/sessions");
}

export function getSession(sessionId: string): Promise<SessionDetail> {
  return getJSON<SessionDetail>(`/sessions/${encodeURIComponent(sessionId)}`);
}

export function deleteSession(sessionId: string): Promise<void> {
  return deleteJSON(`/sessions/${encodeURIComponent(sessionId)}`);
}

export async function askQuery(
  question: string,
  filters: Record<string, string> | null = null,
  session_id: string | null = null,
  signal?: AbortSignal,
  // POST /query runs the full synthesis pipeline (server budget: llm_timeout_s
  // x retries can exceed 30s), so the stream-failure fallback passes the same
  // LONG bound the stream attempt got — otherwise the client aborts while the
  // server completes and persists the turn invisibly.
  timeoutMs: number = DEFAULT_TIMEOUT_MS,
): Promise<QueryResponse> {
  return normalizeQuery(
    await postJSON<QueryResponse>("/query", { question, filters, session_id }, true, signal, timeoutMs),
  );
}

function isAbortError(e: unknown): boolean {
  // A fetch abort rejects with a DOMException named "AbortError". Match on the
  // name alone, not `instanceof Error`: in browsers DOMException extends Error,
  // but in some runtimes (jsdom/older Node) it does NOT, and a name check there
  // is the only reliable signal. We require an object with that exact name.
  return typeof e === "object" && e !== null && (e as { name?: unknown }).name === "AbortError";
}

// Callbacks for the streamed ask: cosmetic status lines and provisional answer
// deltas. Both are best-effort; neither is the authoritative answer — that is the
// single terminal `result` frame (post citation-validation).
export interface StreamCallbacks {
  onStatus?: (text: string) => void;
  onToken?: (delta: string) => void;
}

// Status line emitted immediately before every stream-failure fallback to plain
// POST /query. The page keys off this exact string to discard the provisional
// draft accumulated from the dead stream (its tokens are contractually
// discarded on fallback) and show progress for the re-run instead.
export const STREAM_FALLBACK_STATUS = "Retrying without streaming...";

// Minimal text/event-stream reader for /query/stream. Frames per the pinned
// contract: zero or more `event: status` / `data: {"text": …}` and `event: token`
// / `data: {"delta": …}` (provisional answer text), then exactly one
// `event: result` whose data is the full validated QueryResponse, then close.
// Returns null if the stream closes without a result frame (caller falls back to
// plain /query).
// Inactivity watchdog for the SSE body read. The TTFB timer is disarmed once
// headers arrive, so without this a half-open connection (AP roam, proxy or
// machine death without RST) would leave reader.read() pending forever with no
// error and no fallback. The server emits a keep-alive comment every ~15s, so a
// healthy stream always has traffic well inside this window; 75s of total
// silence means the connection is dead.
const SSE_IDLE_TIMEOUT_MS = 75_000;

async function consumeSse(
  body: ReadableStream<Uint8Array>,
  callbacks?: StreamCallbacks,
): Promise<QueryResponse | null> {
  const reader = body.getReader();
  const decoder = new TextDecoder();
  let buf = "";
  let eventName = "";
  let data = "";

  // On expiry cancel the reader: the pending read resolves done, the loop ends
  // without a result, and the caller's /query fallback takes over. Re-armed on
  // EVERY chunk, keep-alive comments included.
  let idleTimer: ReturnType<typeof setTimeout> | null = null;
  const armIdle = () => {
    if (idleTimer !== null) clearTimeout(idleTimer);
    idleTimer = setTimeout(() => void reader.cancel().catch(() => {}), SSE_IDLE_TIMEOUT_MS);
  };

  const dispatch = (): QueryResponse | null => {
    const name = eventName;
    const payload = data;
    eventName = "";
    data = "";
    if (!payload) return null;
    if (name === "status") {
      try {
        const d = JSON.parse(payload) as { text?: unknown };
        if (typeof d.text === "string") callbacks?.onStatus?.(d.text);
      } catch {
        // a malformed status frame is cosmetic — keep reading
      }
      return null;
    }
    if (name === "token") {
      try {
        const d = JSON.parse(payload) as { delta?: unknown };
        if (typeof d.delta === "string") callbacks?.onToken?.(d.delta);
      } catch {
        // a malformed token frame is cosmetic (provisional draft) — keep reading
      }
      return null;
    }
    if (name === "result") return JSON.parse(payload) as QueryResponse;
    return null;
  };

  try {
    armIdle();
    for (;;) {
      const { done, value } = await reader.read();
      if (done) break;
      armIdle();
      buf += decoder.decode(value, { stream: true });
      let nl: number;
      while ((nl = buf.indexOf("\n")) !== -1) {
        let line = buf.slice(0, nl);
        buf = buf.slice(nl + 1);
        if (line.endsWith("\r")) line = line.slice(0, -1);
        if (line === "") {
          const result = dispatch();
          if (result) return result;
          continue;
        }
        if (line.startsWith(":")) continue; // SSE comment / keep-alive
        const colon = line.indexOf(":");
        const field = colon === -1 ? line : line.slice(0, colon);
        let value2 = colon === -1 ? "" : line.slice(colon + 1);
        if (value2.startsWith(" ")) value2 = value2.slice(1);
        if (field === "event") eventName = value2;
        else if (field === "data") data = data ? `${data}\n${value2}` : value2;
        // id:/retry: are irrelevant here
      }
    }
    // Stream closed. Flush any bytes still held in the decoder, then drain a
    // residual final line (a frame whose last line carried no trailing newline
    // — otherwise its data would be lost and the question re-sent on fallback).
    buf += decoder.decode();
    let tail = buf;
    if (tail.endsWith("\r")) tail = tail.slice(0, -1);
    if (tail !== "" && !tail.startsWith(":")) {
      const colon = tail.indexOf(":");
      const field = colon === -1 ? tail : tail.slice(0, colon);
      let value2 = colon === -1 ? "" : tail.slice(colon + 1);
      if (value2.startsWith(" ")) value2 = value2.slice(1);
      if (field === "event") eventName = value2;
      else if (field === "data") data = data ? `${data}\n${value2}` : value2;
    }
    // A trailing record without its blank-line terminator still dispatches.
    return dispatch();
  } finally {
    // Release the watchdog on every exit path (result, clean close, throw,
    // idle-cancel) so no timer can fire after the stream is done.
    if (idleTimer !== null) clearTimeout(idleTimer);
    void reader.cancel().catch(() => {});
  }
}

// Streamed ask. Status frames arrive via onStatus while the backend works;
// resolves with the same QueryResponse shape as askQuery. Any stream-level
// failure (endpoint missing, proxy buffering, mid-stream error, stream closed
// without a result frame) falls back to plain POST /query transparently — the
// pinned contract accepts that a mid-stream fallback re-runs the question.
// An abort (new chat / session switch) is NOT a failure: it rethrows so the
// caller can discard the turn instead of double-sending.
export async function askQueryStream(
  question: string,
  filters: Record<string, string> | null = null,
  session_id: string | null = null,
  callbacks?: StreamCallbacks,
  signal?: AbortSignal,
): Promise<QueryResponse> {
  const path = "/query/stream";
  if (signal?.aborted) throw new DOMException("aborted", "AbortError");

  // The stream bound covers only TIME-TO-FIRST-BYTE: a backend that never
  // sends response headers can't leave the page spinning forever. Once headers
  // arrive the timer is cleared and the body may legitimately stream for a
  // while. We can't pass the caller signal directly because the timer must
  // abort too, so we forward caller-cancel onto our own controller and keep
  // that forwarding alive for the WHOLE stream lifetime (cleaned up in the
  // outer finally) — that's what lets user-cancel still abort the body read in
  // consumeSse mid-stream, exactly as before.
  const ctl = new AbortController();
  let ttfbTimedOut = false;
  let ttfbTimer: ReturnType<typeof setTimeout> | null = setTimeout(() => {
    ttfbTimedOut = true;
    ctl.abort();
  }, LONG_TIMEOUT_MS);
  const onCallerAbortStream = () => ctl.abort();
  signal?.addEventListener("abort", onCallerAbortStream, { once: true });

  try {
    let res: Response;
    try {
      res = await fetch(`${apiBase()}${path}`, {
        method: "POST",
        headers: { "Content-Type": "application/json", Accept: "text/event-stream" },
        body: JSON.stringify({ question, filters, session_id }),
        credentials: "include",
        signal: ctl.signal,
      });
    } catch (e) {
      // Headers never arrived. A real caller abort rethrows; the TTFB timer
      // firing is a defined failure that surfaces (don't re-run the long call);
      // any other network error falls back to plain /query as before.
      if (signal?.aborted) throw new DOMException("aborted", "AbortError");
      if (ttfbTimedOut) {
        throw new ApiError(TIMEOUT_STATUS, "The request timed out — please try again.");
      }
      if (isAbortError(e)) throw e;
      callbacks?.onStatus?.(STREAM_FALLBACK_STATUS);
      return askQuery(question, filters, session_id, signal, LONG_TIMEOUT_MS);
    } finally {
      // Headers are in (or the fetch failed): disarm the TTFB timer. The
      // caller-abort forwarding stays wired so the body read can still cancel.
      if (ttfbTimer !== null) {
        clearTimeout(ttfbTimer);
        ttfbTimer = null;
      }
    }
    if (res.status === 401) {
      onUnauthorized?.();
      throw new ApiError(401, "authentication required");
    }
    const contentType = (res.headers.get("content-type") ?? "").toLowerCase();
    if (!res.ok || !res.body || !contentType.includes("text/event-stream")) {
      // 404/405 (endpoint not deployed yet) or a non-streaming response. Cancel
      // the body so a stray non-SSE stream can't run alongside the fallback.
      void res.body?.cancel().catch(() => {});
      callbacks?.onStatus?.(STREAM_FALLBACK_STATUS);
      return askQuery(question, filters, session_id, signal, LONG_TIMEOUT_MS);
    }
    try {
      const result = await consumeSse(res.body, callbacks);
      if (result) return normalizeQuery(result);
    } catch (e) {
      if (isAbortError(e)) throw e;
      // fall through to the plain call
    }
    if (signal?.aborted) throw new DOMException("aborted", "AbortError");
    callbacks?.onStatus?.(STREAM_FALLBACK_STATUS);
    return askQuery(question, filters, session_id, signal, LONG_TIMEOUT_MS);
  } finally {
    // Always release the timer (if the fetch path above didn't reach its own
    // finally) and the caller-abort listener — no leak on any path.
    if (ttfbTimer !== null) clearTimeout(ttfbTimer);
    signal?.removeEventListener("abort", onCallerAbortStream);
  }
}

export function assemble(
  active_ingredient: string,
  dosage_form: string | null = null,
  rld: string | null = null,
): Promise<AssembleResponse> {
  return postJSON<AssembleResponse>("/assemble", { active_ingredient, dosage_form, rld });
}

export function buildWhitepaper(
  rldName: string,
  applicationNumber: string,
): Promise<WhitepaperResponse> {
  // A 422 here is the resolution-failure contract: detail explains what WAS
  // found — surface it verbatim, never retry with a guess.
  return postJSON<WhitepaperResponse>("/whitepaper", {
    rld_name: rldName,
    application_number: applicationNumber,
  });
}

// Validate an RLD name + application number into the canonical spine, without
// running a populate. Deterministic entity resolution — the backend writes no
// audit row and returns no answer text. Same 422 contract as buildWhitepaper:
// `detail` explains what WAS found; postJSON surfaces it as an ApiError, never
// a guess. Returns the bare spine.
export function resolveProduct(
  rldName: string,
  applicationNumber: string,
): Promise<WhitepaperSpine> {
  return postJSON<WhitepaperSpine>("/resolve", {
    rld_name: rldName,
    application_number: applicationNumber,
  });
}

// Content-Disposition: attachment; filename=whitepaper_020503.docx — also
// tolerates the quoted and RFC 5987 (filename*=UTF-8''…) forms.
function filenameFromDisposition(header: string | null): string | null {
  if (!header) return null;
  const star = /filename\*\s*=\s*(?:UTF-8'')?([^;]+)/i.exec(header);
  if (star) {
    try {
      return decodeURIComponent(star[1].trim().replace(/^"+|"+$/g, ""));
    } catch {
      // malformed encoding — fall through to the plain form
    }
  }
  const plain = /filename\s*=\s*"?([^";]+)"?/i.exec(header);
  return plain ? plain[1].trim() : null;
}

// Org-shared saved runs, newest activity first. Filters are passed through to
// the server (an unparseable application_number filter 422s -- refuse, never
// guess); pagination mirrors /watch/latest's count/total/limit/offset honesty.
export function listWhitepaperRuns(
  params: {
    limit?: number;
    offset?: number;
    application_number?: string;
    normalized_name?: string;
    status?: string;
  } = {},
): Promise<WhitepaperRunList> {
  const qs = new URLSearchParams();
  if (params.limit !== undefined) qs.set("limit", String(params.limit));
  if (params.offset !== undefined) qs.set("offset", String(params.offset));
  if (params.application_number) qs.set("application_number", params.application_number);
  if (params.normalized_name) qs.set("normalized_name", params.normalized_name);
  if (params.status) qs.set("status", params.status);
  const q = qs.toString();
  return getJSON<WhitepaperRunList>(`/whitepaper/runs${q ? `?${q}` : ""}`);
}

export function getWhitepaperRun(runId: number): Promise<WhitepaperRunDetail> {
  return getJSON<WhitepaperRunDetail>(`/whitepaper/runs/${runId}`);
}

// Set one attributed analyst overlay cell. The generated layer is never
// touched (INV-3): the value lives in a separate overlay keyed by cell id, and
// the response carries the stored view (author + updated_at) for attribution.
export function saveWhitepaperInput(
  runId: number,
  cellId: string,
  value: string,
): Promise<WhitepaperCellSaved> {
  return postJSON<WhitepaperCellSaved>(
    `/whitepaper/runs/${runId}/cells/${encodeURIComponent(cellId)}`,
    { value },
  );
}

// Clearing deletes the overlay row (the wire contract: a null value clears);
// the response comes back cleared=true with input=null.
export function clearWhitepaperInput(runId: number, cellId: string): Promise<WhitepaperCellSaved> {
  return postJSON<WhitepaperCellSaved>(
    `/whitepaper/runs/${runId}/cells/${encodeURIComponent(cellId)}`,
    { value: null },
  );
}

export function finalizeWhitepaperRun(runId: number): Promise<WhitepaperRunStatus> {
  return postJSON<WhitepaperRunStatus>(`/whitepaper/runs/${runId}/finalize`, {});
}

export function reopenWhitepaperRun(runId: number): Promise<WhitepaperRunStatus> {
  return postJSON<WhitepaperRunStatus>(`/whitepaper/runs/${runId}/reopen`, {});
}

// Creator-only, drafts-only: the server owns the rules (403 foreign, 409
// final); the page surfaces those as inline messages rather than hiding the
// affordance (the client does not know the current user id).
export function deleteWhitepaperRun(runId: number): Promise<void> {
  return deleteJSON(`/whitepaper/runs/${runId}`);
}

// Renders the .docx server-side FROM the saved run (no client echo, no
// re-populate): the server re-verifies the stored sections fingerprint before
// rendering, so the document can never silently differ from what the analysts
// reviewed. The 200 is the .docx itself: read it as a blob and hand it to the
// browser as a download under the server's Content-Disposition filename.
// Error bodies are JSON, so they go through the shared handler -- same 401
// gate and detail parsing as every other call. applicationNumber only feeds
// the filename fallback when the header is missing/unparseable.
export async function downloadWhitepaperDocx(
  runId: number,
  applicationNumber: string,
): Promise<void> {
  const path = `/whitepaper/runs/${runId}/docx`;
  const res = await fetchWithTimeout(
    `${apiBase()}${path}`,
    { method: "POST", credentials: "include" },
    LONG_TIMEOUT_MS,
  );
  if (!res.ok) {
    await handle<never>(res, "POST", path, true); // always throws
    return;
  }
  const blob = await res.blob();
  const fallback = `whitepaper_${applicationNumber}.docx`;
  const filename = filenameFromDisposition(res.headers.get("content-disposition")) ?? fallback;
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = filename;
  document.body.appendChild(anchor);
  anchor.click();
  anchor.remove();
  // Revoking in the same tick aborts the download in WebKit -- defer until the
  // browser has had a chance to start streaming the blob.
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

// Answer feedback: rating is exactly +1 (helpful) or -1 (not helpful); the
// server upserts per (audit_id, user) so re-rating — or re-sending with a
// comment attached — replaces the previous row rather than stacking. A 404
// means the audit row isn't the caller's own qa answer; surfaced like any
// other ApiError. Response body is ignored on purpose: success is the signal.
export async function sendFeedback(
  auditId: number,
  rating: 1 | -1,
  comment: string | null = null,
): Promise<void> {
  await postJSON<unknown>("/feedback", { audit_id: auditId, rating, comment });
}

export function watchLatest(): Promise<WatchLatest> {
  return getJSON<WatchLatest>("/watch/latest");
}

export function listProducts(): Promise<ProductsResponse> {
  return getJSON<ProductsResponse>("/products");
}

export function getPublicSettings(): Promise<PublicSettings> {
  return getJSON<PublicSettings>("/settings");
}
